### ISSUE TITLE
`on_open` doesn't perform correctly

### ISSUE THREAD

**Issue by meijieru** [akinsho/toggleterm.nvim#108]
The `on_open` hook doesn't take effect.

Steps to reproduce:
1. with the following config
2. execute `:lua require('telescope').extensions.asynctasks.all()`
3. select the item

Expect: The terminal is in insert mode
Actual: The terminal is in normal mode

What I have tried
1. Directly run `:AsyncTask file-repl` is OK
2. I manually insert some `vim.fn.input` [within the code](https://github.com/akinsho/toggleterm.nvim/blob/5f9ba91157a25be5ee7395fbc11b1a8f25938365/lua/toggleterm/terminal.lua#L346). When executed to here, the terminal still doesn't prompt.

Here is the minimal config

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
Plug 'skywind3000/asynctasks.vim'
Plug 'skywind3000/asyncrun.vim'
Plug 'GustavoKatel/telescope-asynctasks.nvim'
Plug 'akinsho/toggleterm.nvim'
call plug#end()
PlugInstall | quit

lua require("toggleterm").setup{}

lua << EOF
local terminal = require("toggleterm.terminal").Terminal

M = {}

function M.runner(cmd, dir, mapping)
    M._asynctask_term = terminal:new({
        cmd = cmd,
        dir = dir,
        close_on_exit = false,
        hidden = true,
        on_open = function (_)
            vim.cmd("startinsert!")
        end
    })

    function M._asynctask_term_toggle()
        M._asynctask_term:toggle()
    end

    M._asynctask_term_toggle()
end

EOF

function! s:toogle_term_runner(opts)
    lua M.runner(vim.fn.eval("a:opts.cmd"), vim.fn.eval("a:opts.cwd"))
endfunction

let g:asyncrun_runner = get(g:, 'asyncrun_runner', {})
let g:asyncrun_runner.toggleterm = function('s:toogle_term_runner')
let g:asynctasks_term_pos = 'toggleterm' 

```

The asynctasks config file `~/.config/nvim/tasks.ini`
```ini
[file-repl]
command="ipython"
output=terminal
```

**Comment by akinsho** [comment]
@meijieru sorry I'm quite confused by this issue since it seems to involve using another plugin I don't know anything about, so it's not clear to me how the terminal is being toggled when used like this. Can you reproduce this issue in a minimal environment without this other plugin i.e. just toggle a normal terminal and add an on open command? I have on open commands in my config which definitely work, so it's likely some complexity to do with this other plugin somehow.

**Comment by meijieru** [comment]
@akinsho I tried to simplify it as much as possible and currently no interaction with `asynctask.vim` and `asyncrun.vim`.
 [telescope-asynctasks](https://github.com/GustavoKatel/telescope-asynctasks.nvim) is a short one file script which is an extension of [telescope](https://github.com/nvim-telescope/telescope.nvim).
The fake `asynctasks` doesn't care about the input and try to run `ipython` anyway.
So currently there is only interaction between telescope and toggleterm.


vimrc.vim
```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
execute 'set runtimepath+=' . '/tmp'
call plug#begin(s:plug_dir)
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
Plug 'GustavoKatel/telescope-asynctasks.nvim'
Plug 'akinsho/toggleterm.nvim'
call plug#end()
PlugInstall | quit

lua require("toggleterm").setup{}

lua << EOF
local terminal = require("toggleterm.terminal").Terminal

M = {}

function M.runner(cmd, dir, mapping)
    M._asynctask_term = terminal:new({
        cmd = cmd,
        dir = dir,
        close_on_exit = false,
        hidden = true,
        on_open = function (_)
            vim.cmd("startinsert!")
        end
    })

    function M._asynctask_term_toggle()
        M._asynctask_term:toggle()
    end

    M._asynctask_term_toggle()
end

EOF

command! -bang -nargs=1 -range=0 AsyncTask
      \ lua M.runner("ipython", "/tmp")
```

`/tmp/autoload/asynctasks.vim`
```vim
function! asynctasks#source(opt)
  return  [[ 'file-repl    ', '<global>', 'ipython' ]]
endfunction
```

`~/.config/nvim/tasks.ini`
```ini
[file-repl]
command="ipython"
output=terminal
```

**Comment by meijieru** [comment]
One observation is that when executing `on_open`, the terminal buffer is not opened yet.
Not sure whether it is related.

**Comment by akinsho** [comment]
@meijieru thanks but I'm still not sure I can follow the flow here as there's some implicit knowledge of what asynctasks might be trying to do that I don't understand. If you create terminal as you have done above and simply call toggle on it later that e.g. directly call the `asynctask_term_toggle()` function that should work and a similar setup works for me. I don't know what the `tasks.ini` does or why the autoloaded function is there etc.

If the terminal buffer doesn't open, then `on_open` won't work, since it is called after the terminal is open. It could be that an error is being thrown somewhere, but there are still a lot of layers here that I don't follow

**Comment by meijieru** [comment]
The tasks.ini and autoload function is required by the `telescope-asynctasks`.
So they are corporate to simulate the usage with `telescope.nvim`.

>If the terminal buffer doesn't open, then on_open won't work, since it is called after the terminal is open. It could be that an error is being thrown somewhere, but there are still a lot of layers here that I don't follow

I mean the `on_open` function is called before  the terminal buffer opened.

**Comment by akinsho** [comment]
@meijieru tbh I don't really have the bandwidth to investigate this atm, especially since it's not exactly clear to me how to reproduce this issue with just this plugin. If you want to try and debug this on your end the line where `on_open` is called is https://github.com/akinsho/toggleterm.nvim/blob/0b6d65d8b45e261bc17176e86abb3f631c88fc1b/lua/toggleterm/terminal.lua#L345
and the split should be opened if possible just above it https://github.com/akinsho/toggleterm.nvim/blob/0b6d65d8b45e261bc17176e86abb3f631c88fc1b/lua/toggleterm/terminal.lua#L333-L336
as you can see `on_open` shouldn't be called if `opener` fails to open a window somehow and this should be reported using `vim.notify`.

I'm not sure why you are not seeing the window open, but `on_open` is being called anyway rather than an error being printed

**Comment by meijieru** [comment]
Thanks for the guidance.

**Comment by meijieru** [comment]
Doesn't observe the problem in the recent version.
