### ISSUE TITLE
[Bug] TermExec passes null instead of string on Windows

### ISSUE THREAD

**Issue by kishikaisei** [akinsho/toggleterm.nvim#110]
When using `termexec cmd='anything'` it passes `null` to the terminal instead of `anything` and it doesn't even run it:

![ezgif-5-78b0f6af5e25](https://user-images.githubusercontent.com/1894123/141064252-11081a0f-2031-4d20-93fa-54f0809ca9d9.gif)

I am on windows, and it the same thing if I am using `cmd` or `pwsh`.

**Comment by akinsho** [comment]
@kishikaisei this is likely a windows related bug since when I do the same thing on macos and Ubuntu I get the expected behaviour. As I've mentioned in quite a few issues in the past I'm not a windows user so don't know anything about what is required to make functionality work on that platform so I depend *entirely on windows users* for PRs to debug and fix windows related functionality.

In this case I have no way of testing this since I don't own a windows machine so can't debug what you're seeing. One place that might be worth looking is https://github.com/akinsho/toggleterm.nvim/blob/0b6d65d8b45e261bc17176e86abb3f631c88fc1b/lua/toggleterm/commandline.lua#L27

This code was contributed by a windows user to fix some issues with parsing command line arguments, it could be that your version of lua doesn't have `jit` so 2 things I recommend trying are first trying to use double quotes instead of single and second checking if you have `jit` in your version of lua by doing something like `:lua print(vim.inspect(jit))`

**Comment by kishikaisei** [comment]
I do have JIT (LuaJIT 2.1.0-beta3), and double quotes have the same behaviour.
I will try to make a PR, but no promises, as I have not much time, nor experience with this :)

**Comment by celediel** [comment]
Setting `shellslash` at start up by adding `set shellslash` to vimrc or `vim.g.shellslash = true` to init.vim will send the command to the terminal, but doesn't execute it. I've submitted PR #157 to fix the executing of the command, by replacing \n with \r\n for cmd or \r for powershell.

**Comment by PanagiotisS** [comment]
I came across this plugin today and attempting to use it I had the same issue.

I am not familiar with neovim's lua interface so please bear with me.

According to neovim help for options https://neovim.io/doc/user/lua.html#lua-vim-options
and how the value can be accessed using https://neovim.io/doc/user/lua.html#vim.opt:get()

However looking at the source code we have,

https://github.com/akinsho/toggleterm.nvim/blob/master/lua/toggleterm/commandline.lua#L28

```lua
or vim.g.shellslash == "yes" and quotes
```

Testing the commands 

- open neovim with: `nvim -u NONE`

```vim
:lua print(vim.g.shellslash) " nil
:lua print(vim.opt.shellslash:get()) " false
:set shellslash
:lua print(vim.g.shellslash) " nil
:lua print(vim.opt.shellslash:get()) " true
```

So if we change the following to
https://github.com/akinsho/toggleterm.nvim/blob/master/lua/toggleterm/commandline.lua#L28

```vim
vim.opt.shellslash:get() == false
```

Now it works on my computer with both cmd or powershell, shellslash or noshellslash
- cmd + shellslash
- cmd + noshellslash
- powershell + shellslash
- powershell + noshellslash

```
:version
NVIM v0.6.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az152-430

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

toggleterm commit: `4e350340e2fce27465fa9cc6b6a9f94c7f1e60de`

**Comment by akinsho** [comment]
@PanagiotisS thanks for digging in and posting this. I'm on mac, so I can't actually test any of this stuff out at all. The `shellslash` option isn't available at all on mac so trying to run that command just errors. I've tweaked it to match what you describe though, hopefully that works for other people 👍🏿
