### ISSUE TITLE
Feature: match current colorscheme/theme 

### ISSUE THREAD

**Issue by gacallea** [akinsho/toggleterm.nvim#112]
hi :)

first things first: thank you for this plugin.

Would it be possible to match neovim theme/colorscheme that one has set?

thank you

**Comment by akinsho** [comment]
@gacallea this needs more clarification, i.e. what you mean by match the colorscheme. By default, a neovim colorscheme can set terminal colours and a terminal will by default match the colorscheme or be tweaked by the colorscheme author. What this plugin does is darken the terminal colour to look different, it does not apply colours or re-style the terminal. This is not the objective of this plugin, the entire idea is just to make it clear that a terminal is a terminal when opened, not just another split.

I'm not sure there is anything to do here, since if the desire is to make the terminal look like the rest of vim that should happen automatically or be done by the colorscheme author. If you mean adding new highlight groups or changing the colours for that buffer other than shading the buffer, then no, that's not something this plugin will do.

**Comment by gacallea** [comment]
@akinsho I see. would it be possible to add an option beside 'darken' to 'match' the current neovim theme/colorscheme? I understand it's very much by design to make it look different, but it would be nice to have the choice.

btw this happens already by default when float is set. only horizontal and vertical look different.

please and thank you

**Comment by akinsho** [comment]
@gacallea this doesn't require a new feature, as it is already possible to turn off the shading. This is documented in the README, if you set `shade_terminals = false` this plugin will leave the highlighting alone and not darken  it. To be clear this plugin will not set specific highlights for the terminal or anything it will either shade it or leave it be, those are the only options, I won't implement custom colouring logic for the terminal.

**Comment by gacallea** [comment]
@akinsho so sorry! I didn't understand that. :(
