### ISSUE TITLE
Support: Open/Toggle Multiple terminals at the same time

### ISSUE THREAD

**Issue by captainko** [akinsho/toggleterm.nvim#115]
Hi @akinsho.
 I would like to open/close 3 terminals at the same time like the image below.
![image](https://user-images.githubusercontent.com/32269291/142854556-3c36e711-8808-4361-a32b-5bcd28ea3d4a.png)
Please tell me if there's a way to achieve this. Thanks.

**Comment by akinsho** [comment]
Hi, @captainko there is already a command for this called `ToggleTermToggleAll`, it should already be documented in the README. Gonna close this since there is already a solution

**Comment by trangcongthanh** [comment]
Can `ToggleTermToggleAll` create a new term if no term buffer exists rather than toggle only? Or a new command that combines open_mapping and `ToggleTermToggleAll`. I don't want to bind another key for toggle all only. I need to think twice and keep toggle nothing every time :(

**Comment by akinsho** [comment]
@trangcongthanh I don't think I'll add this since it seems like a slightly niche use case/ very focused to your workflow and maybe not as generally applicable it also doesn't match the intention of those commands. Presumably if you don't have a terminal open you should not use toggle all but instead just use the open mapping 🤷🏿 . I think adding more complexity to this plugin in order to avoid one extra user keymap for a specific scenario isn't a good enough reason to adjust this.

**Comment by trangcongthanh** [comment]
I knew that look like only for my workflow. AFAIK, VSCode, and JetBrains's products had a shortcut to create the first terminal or toggle all of them. I only want to replicate that behavior.

Before I put a comment here, I already tried to do that from userspace. It has not worked yet. My idea: 
- Create a custom function
- Get current count (it's not reliable but maybe works for my case)
- Invoke cmd `ToggleTerm` or `ToggleTermToggleAll`.

I'll read the source and give it a try from userspace before sticking with two keys binding ;)
