### ISSUE TITLE
Opening files from the terminal to be edited in neovim

### ISSUE THREAD

**Issue by LamprosPitsillos** [akinsho/toggleterm.nvim#121]
I find myself almost all the time navigating through the terminal opening a file in terminal to edit it using `nvim` and having the terminal become a mess (nvim inside nvim with no way of quiting out ) .Is there a way for it to recognize that it's opening a file and send it in any of your buffer?
I think the `vifm` plugin does something similar.

**Comment by akinsho** [comment]
@LamprosPitsillos so this problem is actually way beyond the scope of this plugin, since it's essentially about how nvim terminals handle nested sessions. There are some issues in nvim relating to this, but there have been solution available for a while.

I personally recommend using https://github.com/mhinz/neovim-remote (built by an nvim contributor) with this setup then when you open a file from a terminal buffer it will open in your existing nvim session.

**Comment by palandovalex** [comment]
I think this problem can be solved without this mess, just inside vim it self.In this inside terminals - there must be aliases:

alias nvim=nvr --remote

Or if it is inside lunarvim -

alias lvim = nvr --remote

**Comment by akinsho** [comment]
I'm going to close this out since it's been a while and I believe my comment above resolves this issue/clarifies that it doesn't directly relate to this plugin IMO
