### ISSUE TITLE
[Feature request] send popup when task ending

### ISSUE THREAD

**Issue by grimgort** [akinsho/toggleterm.nvim#126]
Hello, 
it would be great if there was a popup to warn that a task of the terminal ends. Like in https://github.com/jlesquembre/nterm.nvim but with other terminals (i use powershell).
Maybe the task is too complex but I ask that in case.

**Comment by akinsho** [comment]
@grimgort I think this is possible by hooking into the `on_exit` event of each terminal which we already do in this plugin but this plugin doesn't natively create popup notification and I'm not going to create custom pop ui for this plugin tbh. It's definitely doable but tbh not something I'm immediately personally inclined to add. If you want to contribute a PR that optionally adds this logic using something like `vim.notify` then I can help guide it. Otherwise it's a bit to fancy and out of scope for my liking (which is not a hard veto just something I don't think is really necessary personally)

**Comment by akinsho** [comment]
I don't think this is something that can be provided generally, it's really not clear where we would intervene to throw up some sort of notification 
I think this is probably better left to the user using global `on_stdout` or `on_exit` commands. If someone has a good idea for how to do this consistently for every
terminal in a way that won't be obtrusive I'm all ears but otherwise going to close this out. Feel free to comment with a strategy for how to implement this in the future.
