### ISSUE TITLE
Float position

### ISSUE THREAD

**Issue by fedoranvar** [akinsho/toggleterm.nvim#129]
Good day to you!

is it possible to set position of float window: 
top-left corner (x,y) of float or anchoring by side (North, NorthEast, East, etc.) ?

Thank you!

**Comment by akinsho** [comment]
@fedoranvar this is currently not supported but ultimately would be about adding the fields to the config object and then passing them to where the window is opened so not complicated to do. I personally am not going to add this in the near future as I don't have the time and am less convinced for the need of this but am very open to a PR since I can see that eventually someone else might want this.

**Comment by fedoranvar** [comment]
got it.

Thank you!

**Comment by c02y** [comment]
Using this to get right-bottom floating terminal with 50% of the width/height of current vim buffer window:
```
float_opts = {
	width = function(_term)
		local width = math.ceil(vim.o.columns / 2)
		_term.float_opts.col = vim.o.columns - width
		return width
	end,
	height = function(_term)
		local height = math.ceil(vim.o.lines / 2)
		_term.float_opts.row = vim.o.lines - height
		return height
	end,
}
```
