### ISSUE TITLE
Not rendering  partly previous log when toggling the terminal

### ISSUE THREAD

**Issue by QiyJarw** [akinsho/toggleterm.nvim#136]
# Not rendering  partly previous log when toggling the terminal
Hi, I'm using this plugin to comfortable dev-life. 
When I toggle a terminal, part of the previous output isn't shown, and command-line rendering collapses like the screenshot below.

![image](https://user-images.githubusercontent.com/38282544/147799847-756fdc88-aaa6-43d5-9ac1-c3b97b983ecc.png)

## Environment
- OS: Win 10 Home
- Shell: PowerShell Core 
- Using the custom prompt; starship

toggleterm.nvim config:

```lua
require('toggleterm').setup{
	-- size = 14, -- ターミナルのサイズ
	open_mapping = [[<c-t>]],
	hide_numbers = true,
	-- shade_filetypes = {},
	shade_terminals = true,
	start_in_insert = true, --ターミナルを開いた時にインサートモードで入る
	insert_mappings = true,
	persist_size = true,
	direction = 'float', --ターミナルを開く方式
	close_on_exit = true, --プロセスをキルしたときにウィンドウを閉じる
	shell = vim.o.shell, --シェルの設定
	-- float ウィンドウ時の設定
	float_opts = {
		border = 'curved',
		width = 120,
		height = 30,
		winblend = 0, --custom promptが崩れるため0に設定
		highlights = {
			border = "Normal",
			background = "Normal"
		}
	}
}
vim.api.nvim_set_keymap('t','jj','<C-\\><C-n>',{noremap = true})
```

**Comment by akinsho** [comment]
Hi @QiyJarw so this looks like an issue with the terminal in neovim and not really with this plugin. For context this plugin just changes how the built-in terminal is shown, it doesn't touch the actual behaviour of the underlying terminal, so I don't have control of how the content of the terminal e.g. prompts and such are shown. TLDR I don't really know how to help since I don't think this problem comes from this plugin specifically.

**Comment by QiyJarw** [comment]
@akinsho I see... thank you for replying! 😄

**Comment by akinsho** [comment]
Going to close this out since I don't think this issue comes from a bug in this plugin but rather nvim's terminal/the running programs behaviour
