### ISSUE TITLE
[feature] scroll Terminal on output automatically

### ISSUE THREAD

**Issue by Patrick-web** [akinsho/toggleterm.nvim#143]
I always have to switch to the terminal and scroll down to see new output. I would love if this was done automatically.

**Comment by akinsho** [comment]
Hi @Patrick-web, so I currently maintain this plugin on my own and as such I clarify in the README that if users want certain functionality if they should investigate opening a pull request rather than a feature request. I maintain this as well as several other plugins, so can't add every feature I get requested across all my plugins on my own. 

Personally scrolling to the new output for me is as simple as pressing `G` in normal mode so doesn't really seem to need complex auto scrolling logic but if you are able to work out a solution I'd be happy to review a PR

**Comment by Patrick-web** [comment]
I totally understand. I'll look into add it. Thanks for the great work

**Comment by DrPoppyseed** [comment]
Hi, OSS newbie passing by. An option to set autoscrolling on or off would be great, I agree. 
I was wondering if it could be done quite easily with `norm G` [like in neoterm.vim](https://github.com/itmecho/neoterm.nvim/blob/32e0e78bc862b1ef801f43ea050818e79d437155/lua/vterm.lua#L11).

**Comment by akinsho** [comment]
@DrPoppyseed I think as you say this can be added simply but as I mention above I'm a bit busy atm so if people have an idea on how to implement this then I would appreciate a PR which does implement this as an option. It should be as straightforward as adding an on `stdout` handler when a terminal is created which runs `vim.cmd('norm G')` every time something is emitted on stdout, but that would have to also make sure to switch to that buffer first if it is visible. something like `nvim_win_call(NUM, function() vim.cmd('norm G') end)`

**Comment by DrPoppyseed** [comment]
@akinsho Thanks. I can't say for sure how fast I can create the PR, but with your suggestions, I'll try something out!

**Comment by akinsho** [comment]
fixed by #285
