### ISSUE TITLE
Toggle the last terminal when running ToggleTerm

### ISSUE THREAD

**Issue by you-n-g** [akinsho/toggleterm.nvim#147]
Toggleterm is really a great plugin! Thanks for your great efforts.

I have got a scenario like this.
I want to manage 2 terminal sessions.
Currently, if  I want to toggle the second terminal, I have to run `ToggleTerm 2`.

I want to toggle the second terminal by just running `ToggleTerm`  if it is the last terminal  I activated.  (Currently, the first terminal if I run `ToggleTerm`)

Do you have any ideas about how to achieve this?  Thanks

Thanks.

**Comment by akinsho** [comment]
@you-n-g toggle term will toggle the terminal with the highest id first so if you have one that is terminal 1 and one that is 2, then pressing toggleterm should close 2. This is how it behaves on my machine. I won't add a last opened type heuristic because this is complex and error prone tbh and the current behaviour already covers theoretically closing the terminal with the highest buffer id already which should technically be the one opened latest.

**Comment by you-n-g** [comment]
Thanks for your reply

**Comment by you-n-g** [comment]
Finally, I choose  map `<FX>` to  `ToggleTerm X` to meet my requirements.
