### ISSUE TITLE
PDM Pep582 Support

### ISSUE THREAD

**Issue by KarimLeVallois** [akinsho/toggleterm.nvim#170]
I'm running a keybinding command to run Python scripts using { "<cmd>:TermExec cmd='python3 %'<CR>", "Run Python Code In Floating Terminal" }, but need to run eval "$(pdm --pep582)" before I can run any code to set the environment variable. I've tried multiple "cmd" options but cannot get it to work with my macOS Zsh setup. The auto setting of the variable is in my .zprofile and works when running the script through the external terminal iTerm2, just not in Toggleterm. Any ideas on how to get this to work?

https://pdm.fming.dev/

**Comment by akinsho** [comment]
@KarimLeVallois sorry I have no idea about how to get this working. This seems more specific to your terminal setup in general rather than how this plugin or how it works I guess you could try to set your cmd to a combination starting with the `pdm` command but honestly I don't know it seems like something that should be in your `zshenv` or your `zshrc` since `zprofile` is run only for login shells I believe 🤷🏿‍♂️

**Comment by KarimLeVallois** [comment]
I did something REALLY silly! I have a separate .zshrc that I use for Neovim, but I hadn't added the variable to it. Everything works now, sorry to waste your time.
