### ISSUE TITLE
Terminal content disappears when resizing windows

### ISSUE THREAD

**Issue by taraslis453** [akinsho/toggleterm.nvim#177]
See attached video - 

https://user-images.githubusercontent.com/48454662/159067726-559a946f-d735-475d-a7c6-053f513fc54c.mov

**Comment by akinsho** [comment]
@taraslis453 this appears to be a bug with neovim and how it handles the rendering of terminal content. Can you reproduce this bug just using `:terminal` if so, you should report this upstream. In either case this is not something caused by this plugin since it doesn't really touch the actual rendering of the terminal
