### ISSUE TITLE
Custom .zshrc File

### ISSUE THREAD

**Issue by karimlevallois** [akinsho/toggleterm.nvim#188]
I currently have a specific .zshrc file that I use to launch Neovim (no Neofetch included) and have a keybinding to open a terminal window directly to Neovim. However, I want Neofetch to show in the floating terminal when I launch it, so would like this to use my normal .zshrc file. Is that possible?

**Comment by akinsho** [comment]
@karimlevallois this really seems like something that relates specifically to your config and setup and isn't really a bug or issue with this plugin. I'm sure there might be a way to get this to work, but it doesn't really seem directly related to this plugin at all. I'm not really sure why you need to have a whole separate `.zshrc` just to remove neofetch rather than using some sort of if statement, and I'm also not sure why you need to hide it at all, but as I mentioned this seems like one for reddit or nvim discourse rather than a plugin issue.

**Comment by karimlevallois** [comment]
I was just wondering if there was a way to define a path to the .zshrc file similar to what can be done inside the terminal. If not, no worries, happy to close.
