### ISSUE TITLE
Set terminal keymaps only when direction is not float

### ISSUE THREAD

**Issue by zakissimo** [akinsho/toggleterm.nvim#190]
Because I use ```<C-j>``` and ```<C-k>``` to select files or lines in fzf. I only want to activate the following keybinds when the terminal is NOT opened in floating mode.

```lua
function _G.set_terminal_keymaps()
	vim.api.nvim_buf_set_keymap(0, "t", "<C-q>", [[<C-\><C-n>]], opt)
	vim.api.nvim_buf_set_keymap(0, "t", "<C-h>", [[<C-\><C-n><C-W>h]], opt)
	vim.api.nvim_buf_set_keymap(0, "t", "<C-j>", [[<C-\><C-n><C-W>j]], opt)
	vim.api.nvim_buf_set_keymap(0, "t", "<C-k>", [[<C-\><C-n><C-W>k]], opt)
	vim.api.nvim_buf_set_keymap(0, "t", "<C-l>", [[<C-\><C-n><C-W>l]], opt)
end
```

I don't have a lot of experience in lua, I tried different if statements but I don't know how to get to the ```direction``` variable. When I look at ```toggleterm.setup``` i see that it's a function and not a table. Can you please indicate how I can lookup the ```direction``` variable programatically ? Thanks.

**Comment by akinsho** [comment]
@zakissimo I'm going to close this out since this is less an issue and more a question and `win_gettype` would be the answer, not sure if you checked the docs for it already. If you did, you'd see that it returns `popup` when the window is a float, so you can do something like call the set terminal keymap on BufEnter if the type is not popup

```lua
if vim.fn.win_gettype ~= "popup" then
 -- Do logic
end
```

**Comment by zakissimo** [comment]
I just had to add parenthesis to call the function:

```vim.fn.win_gettype()```

And it works exactly like I wanted ;),
Thank you!
