### ISSUE TITLE
Background color issue

### ISSUE THREAD

**Issue by ravenxrz** [akinsho/toggleterm.nvim#193]
Hi, I use zsh with zsh-autosuggestions plugin. 

The image shows the difference between toggleterm(left side) and normal terminal(right side) as I type some text.

![image](https://user-images.githubusercontent.com/44746032/161766554-ad0ad2e2-a332-4540-90ea-bbfc1aa33b64.png)

Is there any way to set the color of "virtual text"  brighter in toggleterm?

**Comment by akinsho** [comment]
Hi @ravenxrz,

To clear up a few things, toggle term doesn't really change the behaviour of nvim's native terminal at all. This is likely just the behaviour of the terminal buffer in a float. It could be for a few reasons 1.) you have `winblend` turned on this could be changing the rendering of suggestions text, 2.) Neovim's terminal when rendered in float does this 🤷🏿‍♂️ 

I would verify whether the behaviour is the same in any other float, and if so you might want to report this upstream. In either case it's very unlikely to be due to a plugin bug since I'm not doing anything to change how the actual text of the terminal buffer is rendered.

**Comment by ravenxrz** [comment]
> Hi @ravenxrz,
> 
> To clear up a few things, toggle term doesn't really change the behaviour of nvim's native terminal at all. This is likely just the behaviour of the terminal buffer in a float. It could be for a few reasons 1.) you have `winblend` turned on this could be changing the rendering of suggestions text, 2.) Neovim's terminal when rendered in float does this 🤷🏿‍♂️
> 
> I would verify whether the behaviour is the same in any other float, and if so you might want to report this upstream. In either case it's very unlikely to be due to a plugin bug since I'm not doing anything to change how the actual text of the terminal buffer is rendered.

Thanks for your reply. 
Now that it's not the behaviour of toggleterm, I will close this issue.

**Comment by chiahsoon** [comment]
> > Hi @ravenxrz,
> > To clear up a few things, toggle term doesn't really change the behaviour of nvim's native terminal at all. This is likely just the behaviour of the terminal buffer in a float. It could be for a few reasons 1.) you have `winblend` turned on this could be changing the rendering of suggestions text, 2.) Neovim's terminal when rendered in float does this 🤷🏿‍♂️
> > I would verify whether the behaviour is the same in any other float, and if so you might want to report this upstream. In either case it's very unlikely to be due to a plugin bug since I'm not doing anything to change how the actual text of the terminal buffer is rendered.
> 
> Thanks for your reply. Now that it's not the behaviour of toggleterm, I will close this issue.

hey @ravenxrz, did u manage to find a fix for this?
