### ISSUE TITLE
Can't disable `shade_terminals`

### ISSUE THREAD

**Issue by eeeXun** [akinsho/toggleterm.nvim#196]
As title. After updating today, I can't disable `shade_terminals`.
Already set the following in config
```lua
require'toggleterm'.setup {
  shade_terminals = false
}
```

**Comment by akinsho** [comment]
I've merged this in now so let me know if that didn't resolve your issue, but in my tests that seemed to have worked

**Comment by akinsho** [comment]
@eeeXun I'm not entirely sure if I understand the issue, when are you setting the highlight group to none? Since this plugin, when setup is called, will get the colour of the normal background at that point and use it as is if shade terminals is false. Are you setting normal to none after this plugin has already been set up?

**Comment by eeeXun** [comment]
@akinsho Yes, I set shade_terminals to false. And set normal to none after this plugin setup.

This is before setting to transparent.
![image](https://user-images.githubusercontent.com/58657914/162185420-ab36bfb2-2c23-4531-9080-a771e8744de3.png)

This is after doing the command
```vim
highlight Normal guibg=NONE ctermbg=NONE
```
![image](https://user-images.githubusercontent.com/58657914/162185587-a191522c-88da-4e0c-96b7-0dc0a67a0b3e.png)

As the picture, the terminal is not transparent.

**Comment by akinsho** [comment]
@eeeXun what I need to confirm is when you set this command? Do you set the command **before** this plugin is setup?

**Comment by eeeXun** [comment]
No, after this plugin is setup.

**Comment by akinsho** [comment]
@eeeXun this plugin can't respond to highlights set after setup, can you switch the highlight command to before this plugin is setup

**Comment by eeeXun** [comment]
Okey. Is due to the new settings, `highlights` added?
Since I can do the command after the pluging is setup before the commit https://github.com/akinsho/toggleterm.nvim/commit/5733b24c684d202f978ccedca4a8c7571889bf28. After this commit, I can't do that.

**Comment by akinsho** [comment]
@eeeXun yes this is because of that, basically another user contributed a feature so that you can set the highlights for different parts of the terminal yourself and also can set highlights for different terminals, so you can have some terminals as black and some as purple etc. For this to work, each terminal needs to have its own highlights, whereas before this each terminal was directly using the highlights from vim instead of their own.

You can try and get the old behaviour by using 
```lua
config.highlights = {
	Normal = {
		link = "Normal",
	}
}
```
Not 100% sure that would work though

**Comment by eeeXun** [comment]
Wow, that actually works.
Totally miss the `link` in the README. Originally thought it refers to url link😂
Thank you for your patiently reply.
