### ISSUE TITLE
[Question] How to 'data exchange neovim<->toggleterm<->terminal program'?

### ISSUE THREAD

**Issue by theCollectiv** [akinsho/toggleterm.nvim#200]
I really like the idea to run terminal programs via toggleterm (i.e. lazygit).
My idea: Using toggleterm with the native terminal program instead of using thousands of neovim-plugins-wrappers doing this. But I'm struggling how to exchange data between neovim<->toggleterm<->terminal program.

Here is some example:
I use ranger (filemanager https://github.com/ranger/ranger) and was using the neovim-wrapper-plugin rnvimr (https://github.com/kevinhwang91/rnvimr) to use ranger inside neovim.

Now I'd like to use it the same way, but with toggleterm + ranger (run by terminal).
But I ran into this issue: If I try to open a file with ranger running in toggleterm, it opens it in the toggleterm-instance instead of opening it in the current neovim-instance.
There is no way to quickfix it (like copying the filepath with ranger to the clipboard in order to open it later in the same neovim-instance, with which I called 'toggleterm' [because the clipboard gets deleted (by the operating system) by closing the program; means "if I'm closing ranger, the clipboard-buffer with the yanked filepath got deleted too ...so I cant use it later in neovim like ':e [filepath]'].

Is something like this possible?
```
local ranger = Terminal:new({
  cmd = "ranger",
  ...
  on_close = function(term)
    vim.cmd(": e [clipboard-yanked-filepath or filepath provided by ranger-function]")
  end,
  ...
})

function _ranger_toggle()
  ranger:toggle()
end

vim.api.nvim_set_keymap("n", "<leader>r", "<cmd>lua _ranger_toggle()<CR>", {noremap = true, silent = true})
```

I can't get it to work the way I want to. So I looked into the "neovim-wrapper-plugin rnvimr"-code, there is RPC used to exchange the data, I guess: Neovim <-> wrapper using rpc <-> ranger

**Comment by akinsho** [comment]
@theCollectiv so I think your specific use case is less about sending data too and from the terminal and more in this case about how to open files in via a terminal program inside neovim. So I'm going to focus on addressing that since rather than something complex like RPC messages etc. there is a well established solution for this.

So *vim* (not neovim) has a series of commands called `--remote` and a bunch of variants like `--remote-wait` etc. these were initially removed when neovim first forked for historical reasons but in the case of the problem this and related commands could have been used to open a file in nested terminal program inside a particular vim instance. 

They are currently in the process of being added back, but that's still WIP, TJ made video about this [here](https://youtu.be/xO5yMutC-rM).

In the short term most people use [neovim-remote](https://github.com/mhinz/neovim-remote), the short version of how this works is that inside of a nvim session you would set your editor to a neovim remote command to open files inside that particular terminal instance. I appreciated this might not all be immediately clear, but neovim remote's README should clarify this stuff. You can then set your terminal program to open files using `$EDITOR`.

Hopefully if you read through neovim remote's README and maybe do some searching on the web you will be able to set this up in your config. I'd personally not want to involve this plugin too much in any of that since although you are opening terminals through this plugin, it isn't actually involved in the underlying workings of your terminal since that is ultimately between you and neovim.

**Comment by theCollectiv** [comment]
@akinsho I'll have a closer look at that. Thx for the answer and giving me some direction to deal with my question.
