### ISSUE TITLE
[Bug] Doesn't respect vim.opt.background after being reopened

### ISSUE THREAD

**Issue by luishfonseca** [akinsho/toggleterm.nvim#208]
My neovim config sets `vim.opt.background="light"` on init.lua.
When I toggle the terminal it displays with the correct colors.

![image](https://user-images.githubusercontent.com/72040432/163724657-f125a3ee-2932-4dd8-8bd9-d29059f4407f.png)

If i change `vim.opt.background` to dark with the terminal open it will change accordingly.

![image](https://user-images.githubusercontent.com/72040432/163724674-b028f33b-0753-4ce9-b561-14383403b396.png)

However, once i close it and open again the background is back to light but the text stays in dark mode making it unreadable.

![image](https://user-images.githubusercontent.com/72040432/163724654-e939cc8d-7671-4112-8e4c-1cef6d90891f.png)

I'm using https://www.lunarvim.org/ with few modifications.
I've turned off `shade_terminals` with no success.

**Comment by akinsho** [comment]
@luishfonseca by default, toggleterm sets the highlights for the terminal once on setup on opening neovim and won't respond to manual changes of `vim.opt.background` since each terminal uses its own highlights. If you want highlights to follow a certain group e.g. `Normal` you can set
```lua
highlights = {
	NormalFloat = {
		link = "Normal"
	},
	FloatBorder = {
		link = "Normal"
	}
}
```
I'm going to make this the default though since this is the third issue of this sort that I've gotten
