### ISSUE TITLE
[Question] How to discard current terminal without setting no hidden without setting nohidden

### ISSUE THREAD

**Issue by MorrisTYB** [akinsho/toggleterm.nvim#209]
Hello, I'm searching for a way to discard the terminal when closed. I often have multiple buffers open each in different dirs, setting `nohidden` will not work well for me. I would like a way to essentially have terminals reset on open, that way I don't have to keep track of which buffer has each terminal

**Comment by akinsho** [comment]
Hi @MorrisTYB tbh I don't really understand at all what the issue is based on what you've said. Do you mean you considered setting `nohidden` as a solution, but having all buffers auto discarded means that isn't a good solution for you?

Also, I don't really understand the use case of always having buffers reset, sort of a core functionality this plugin provides is that your terminals persist rather than it creates a new one each time.

I generally don't know if I could help, since it seems like your use case is fundamentally opposed to what this plugin does. I guess what you could do in your config (which you would need to figure out the details of yourself) is that you could create an autocommand so that whenever you `BufLeave` a terminal buffer it wiped out e.g. `autocmd! BufLeave terminal://* bufwipeout <abuf>` or something like that (please note you will need to actually figure out the autocommand yourself, this is just an example).

**Comment by MorrisTYB** [comment]
> 

Thank you so much for the response! I mean exactly that!! I found a somewhat solution that works similar to present the best of both worlds, because sometimes I do need my terminal to persist even on close. What I did was just alias e='exit' in my .zshrc and set `close_on_exit` to true. I forgot to close this issue last night, but I appreciate the response! Thank you again
