### ISSUE TITLE
How to pass the current working directory as a parameter to a new terminal?

### ISSUE THREAD

**Issue by medwatt** [akinsho/toggleterm.nvim#211]
I am trying to use toggleterm of open the file manager `nnn` from the directory of the current file. I tried to pass `vim.fn.expand('%:p:h')` as the path, but nnn always opens in the same directory. Any ideas how to fix this issue?

```lua
local nnn = Terminal:new {
    dir = vim.fn.expand('%:p:h'),
    cmd = "nnn -goQ",
    direction = "float",
}

function M.nnn_toggle()
    nnn:toggle()
end
```

**Comment by medwatt** [comment]
I think I found something that works. Just needs confirmation if this is the best way to do it:

```lua
function M.nnn_toggle()
    local nnn = Terminal:new {
        dir = vim.fn.expand('%:p:h'),
        cmd = "nnn -goQ",
        direction = "float",
    }
    nnn:toggle()
end
```

**Comment by akinsho** [comment]
The `dir` command is static in the first example, i.e. the value of that variable is equivalent to the value at the time the terminal was made, so it remains the same. The second example will work but will lead to making a new terminal each time, which can get messy. There used to functionality to basically send a `cd <dir>` command if the terminal was already running, but amidst all the feature requests and refactors that got lost. Happy to take a PR for it, but personally not going to do this anytime soon 🤷🏾‍♂️. Hope this answers the question. Going to close this out.

**Comment by zubrailx** [comment]
Just an example with cd:

```lua
local htop = Terminal:new({
    cmd = 'htop',
    hidden = true,
    direction = 'float',
    on_open = float_handler,
})


api.nvim_create_user_command("UsToggleTermLazygit", function() lazygit:toggle() end, {})

```

Call it:
```
:lua vim.env.NVIM_CWD="some path"; vim.cmd("UsToggleTermLazygit")
```

**Comment by zubrailx** [comment]
Example with cd:
```lua
local lazygit = Terminal:new({
    cmd = 'cd $NVIM_CWD && lazygit',
    hidden = true,
    direction = 'float',
    on_open = float_handler,
})
api.nvim_create_user_command("UsToggleTermLazygit", function() lazygit:toggle() end, {})
```
Cmd:
```
<cmd>lua vim.env.NVIM_CWD=vim.fn.getcwd(); vim.cmd("UsToggleTermLazygit")<cr>
```

**Comment by trev-dev** [comment]
I bound the following local function to a normal map binding:

```lua
local Terminal = require("toggleterm.terminal").Terminal

local toggle_lazygit = function() 
  local lazygit = Terminal:new({
    cmd = "lazygit", hidden = true, dir = vim.fn.getcwd()
  })

  lazygit:toggle()
end
```

Works well

**Comment by Paveloom** [comment]
So, after poking around with the source code of the plugin for quite a while, I found out that the easiest way to change the current directory for the terminal is... just do it directly in your `toggle` function:

```lua
-- <...>
-- Setup the plugin
require("toggleterm").setup()
-- Add a `lazygit` terminal
local Terminal = require("toggleterm.terminal").Terminal
local lazygit = Terminal:new({
  cmd = "lazygit",
  hidden = true,
  direction = "float",
  -- <...>
})

-- Toggle the state of the `lazygit` terminal
local function lazygit_toggle()
  -- Sync the current directories of the editor and the terminal
  lazygit.dir = vim.fn.getcwd()
  -- Toggle the terminal
  lazygit:toggle()
end

-- Setup the keybindings
vim.keymap.set("n", "<leader>l", lazygit_toggle, { noremap = true, silent = true })
```

Here are some nuances of this solution:
1) You need something to change the current working directory for you (e.g., `nvim-rooter.lua`).
2) In case of Lazygit, this will only work when you open the new terminal (and not show the hidden one). As far as I can see, there is no (easy) way to *extrernally* change the working directory in Lazygit once it's open (could send a signal to do so otherwise, e.g. via `fn.chansend`).

Also, concerning the first point, there are actually [`autochdir`](https://github.com/akinsho/toggleterm.nvim/blob/3ba683827c623affb4d9aa518e97b34db2623093/lua/toggleterm/terminal.lua#L470), [`https://github.com/akinsho/toggleterm.nvim/blob/3ba683827c623affb4d9aa518e97b34db2623093/lua/toggleterm/terminal.lua#L165`] and `utils.git_dir`, which could be used in case you don't use any other plugins to set your working directory.

However, the `autochdir` check happens only when the terminal already has an attached buffer (which is not a case for closed floating windows), and the `git_dir` function hangs the terminal, at least on my machine.
