### ISSUE TITLE
[upstream] segfault on neovim 0.7.0 

### ISSUE THREAD

**Issue by CaglarDeniz** [akinsho/toggleterm.nvim#212]
I've just upgraded to neovim 0.7.0 from Fedora Rawhide and found out that Toggleterm crashes with a segfault when :ToggleTerm is called. I've included my init.vim file and some system information below.

# System : 
- OS: Fedora 35 
- Kernel Version : 5.15.18
- Shell : bash
- WM : i3
- Terminal : kitty
- Nvim version : 0.7.0

# init.vim 
[init.vim.txt](https://github.com/akinsho/toggleterm.nvim/files/8548771/init.vim.txt)

# Expected Behavior : 
- A floating terminal should appear in nvim
# Problem
- Segfault, nvim crashes, exits to the parent process, visual discrepany. The crashed terminal exists when exit or clear is executed from it.

# Visuals
![visual2](https://user-images.githubusercontent.com/55607471/164949323-f20aeb00-9b91-4174-a59c-cff8d0f7eaa7.png)
![visual1](https://user-images.githubusercontent.com/55607471/164949325-39c4e8fd-2a69-4791-88df-820dd78ef028.png)

**Comment by akinsho** [comment]
Hi @CaglarDeniz,

errors causing neovim to segfault should generally be referred to nvim core, as this plugin is just a visual wrapper for the terminal, so actual bugs with the terminal itself aren't really related to this plugin's functionality. There was a similar issue raised a few weeks ago that the nvim team suggested a workaround for  ⇾ #189 

This might be the root cause for your issue. If not, please raise the issue in nvim and be sure to try to find a minimal reproduction for it.

**Comment by akinsho** [comment]
It's also worth noting that I do not see any segfault on nvim 0.7 so in all likelihood this might relate to your environment as the upstream bug alludes to

**Comment by CaglarDeniz** [comment]
Thank you for the pointer and the advice, I'll make sure to include reproduction steps.
