### ISSUE TITLE
Prevent terminal from leaving Terminal mode

### ISSUE THREAD

**Issue by grech-ca** [akinsho/toggleterm.nvim#217]
https://user-images.githubusercontent.com/54347665/165737701-3aeb9bcc-05ee-4b55-b6d2-f22e94021fea.mov

How do I force single mode for terminal buffer? This annoys me when I want to enter some characters and it leaves Terminal mode

**Comment by akinsho** [comment]
@grech-ca this plugin doesn't do anything to change terminal modes automatically, it looks like you might have some mappings set up in your config that are being triggered here. This isn't default nvim behaviour, since the only way to leave terminal mode in default nvim is something like `<C-N><C-\>` 🤷🏾‍♂️. If you are setting a mapping for your terminal, I suggest removing it or removing it in the on open if you only want to do this for toggleterm.

**Comment by grech-ca** [comment]
@akinsho you're right, my bad, the problem was in mapping
