### ISSUE TITLE
In insert mode, `<C-l>` toggles the terminal (hides it) instead of doing a clear screen

### ISSUE THREAD

**Issue by krishnakumarg1984** [akinsho/toggleterm.nvim#227]
As the title says, with a toggle-term window open and in insert mode, when we press `<C-l>`, we expect it to clear the textual contents of the terminal window. Instead, currently the terminal gets hidden (i.e. toggled).

**Comment by akinsho** [comment]
@krishnakumarg1984 this plugin doesn't create any other mappings in a terminal buffer other than the open mapping, it certainly doesn't map any specific keys by itself without the user specifying something, so there really isn't any reason related directly to this plugin why this would be happening. Can you please open a terminal with the normal `:terminal` command and see if the issue reproduces? If it does, that confirms that this issue is likely related to your configuration and not this plugin.

**Comment by krishnakumarg1984** [comment]
Ok. In a vanilla `:terminal` within `neovim 0.7.0`, I see that `<C-L>` leaves the insert mode to return to normal mode!

However, outside of neovim, in a standard `bash` shell session on my terminal, the `<C-L`> mapping works as expected i.e. it clears the screen.

**Comment by akinsho** [comment]
@krishnakumarg1984 how the `<C-L>` command behaves isn't really the remit of this plugin 🤷🏾‍♂️, this plugin doesn't actually *change* the native terminal behaviour in any way it just opens a terminal in a particular layout, that's all.

**Comment by pasha009** [comment]
For anyone facing similar issue, you can try deleting the keymap for `<C-l>` in terminal mode

`vim.keymap.del("t", "<C-l>")`
