### ISSUE TITLE
Error: ['=' expected near 'continue']

### ISSUE THREAD

**Issue by matcha1024** [akinsho/toggleterm.nvim#228]
![image](https://user-images.githubusercontent.com/67828134/169635101-1fdec5d2-b4ad-4707-a47f-fd4f2520fb18.png)
The image looks like this and `:ToggleTerm` cannot be executed.
The environment is Ubuntu20.04, arm, nvim0.8.0-dev, Lua5.1.
Please help me because I like this project and would love to use it.

**Comment by akinsho** [comment]
@matcha1024 if you look closely at the error message you will note that it mentions luasnip so in so likelihood something relating to luasnip. In your config is broken I recommend starting there.

**Comment by akinsho** [comment]
@matcha1024 I'm going to close this out because from the error message it seems to indicate that you have a syntax error somewhere I don't know why toggleterm is where it's surfacing, but I feel fairly confident it's not related to this plugin, I think if there was a breaking syntax error in this plugin the tests wouldn't be passing and other users would have reported it.
