### ISSUE TITLE
Cannot copy text from terminal to system clipboard

### ISSUE THREAD

**Issue by amit-ug** [akinsho/toggleterm.nvim#233]
I tried copying text both by using `<CMD-c>` and `"*y` and both fail to copy.
I use a mac, and I tried it using both Kitty and the builtin Terminal app.

I tried it previously with NeoVim 0.7 and now with nightly 0.8 as well.

**Comment by akinsho** [comment]
@amit-ug this isn't really an issue specifically for this plugin and is more a question about using neovim's terminal. I recommend having a look at `:help terminal` regarding `<cmd-c>` I think you need to find out how your terminal emulator handles that key since by default cmd-c doesn't copy anything in nvim. In either case this plugin just opens windows and doesn't control mappings or native terminal behaviour

**Comment by akinsho** [comment]
Closing this out as per my above comment
