### ISSUE TITLE
TermExec automatically moves cursor.

### ISSUE THREAD

**Issue by Rid1-fz-06** [akinsho/toggleterm.nvim#237]
I use toggleterm to compile or to run any script. So I binded F9 to a function which uses TermExec command to compile or to run the script. If the terminal split is not opened, it works fine. But if terminal split is opened, whenever I hit F9, cursor automatically moves to the last line of my script 

### To reproduce:
Execute the following command in command mode to bind <f9>

`:nnoremap <f9> :TermExec cmd="python %" direction="horizontal" size=8<cr>`

Now open any python file with at least 2 lines. Move the cursor to very first line and press F9 in normal mode. It will work fine. Now without closing the terminal window, press F9 again.

### Result:
Cursor will automatically be moved to the last line of script.

### Expected Result:
Cursor should have stayed at first line.

**Comment by Rid1-fz-06** [comment]
Duplicate of [#167](https://github.com/akinsho/toggleterm.nvim/issues/167) and feature is not planned.

**Comment by akinsho** [comment]
@Rid1-fz-06 so just to clarify this feature is not planned or unplanned, no features are. I simply extracted logic from my dotfiles and that has grown a lot ever since. I have written in the README and repeated countless times to users that if they want to see functionality, they should consider contributing. This is the same as what I said in the original issue you linked to. I'm quite serious about getting other people to make the contributions they want to see because I simply don't have time to implement every single person's feature request.
