### ISSUE TITLE
Floating window doesn't hide on switch

### ISSUE THREAD

**Issue by ryansch** [akinsho/toggleterm.nvim#246]
This works correctly on `v2.0.0` but does not work as of `ce755e3a07f2464287dc60ed448fdbbe6ea157f5`. I haven't bisected further than that.

Repro:
- Show floating window.
- Try to move "up" via `vim.keymap.set('t', '<C-k>', [[<C-\><C-n><C-W>k]], keymap_opts)`.
- Floating window is now in front of focused content.

**Comment by akinsho** [comment]
@ryansch can you try setting `persist_mode` to false and see if that changes anything. Honestly the commit you point to didn't relate to floats so seems quite odd that they would be working differently

**Comment by ryansch** [comment]
No change. I don't know that it's that commit but rather something in the range: https://github.com/akinsho/toggleterm.nvim/compare/v2.0.0...ce755e3a07f2464287dc60ed448fdbbe6ea157f5

**Comment by himanshugoswamiii** [comment]
Same problem in mine as well after the recent update

**Comment by zbindenren** [comment]
Same problem here...

**Comment by akinsho** [comment]
This should now hopefully be fixed, next time please do not post comments just saying you are experiencing the same issue these are just distracting and noisy and make maintaining this plugin harder since it increases the noise. I maintain several plugins and fix bugs and issues as and when I can. If you are bothered by a bug you can +1 the OPs issue, wait or contribute, *not add same problem comments to the thread*, this is the lease helpful thing to do.

**Comment by ryansch** [comment]
Confirmed fixed.
