### ISSUE TITLE
It doesn't seem to respect `bufferline offset` when used with `bufferline`

### ISSUE THREAD

**Issue by askfiy** [akinsho/toggleterm.nvim#249]
I know these 2 plugins are your masterpieces, you are a respected Neovim plugin developer.

Here, I first express my thanks.

My problem is that it seems that after toggleterm is turned on, the offset -> right of bufferline will be overwritten by bufferline, I think it is caused by toggleterm, so I raised an issue here.

normal circumstances:

![图片](https://user-images.githubusercontent.com/81478335/174648730-e131de7c-3ec3-419c-8ba4-890ff0f676e2.png)

abnormal situation：

![图片](https://user-images.githubusercontent.com/81478335/174648760-f519acd7-d824-4d82-90ba-b76cffe5f192.png)

I don't think he should break the offset setting of the bufferline.

**Comment by akinsho** [comment]
@askfiy the issue is not a bug with toggleterm but a limitation with the offset feature in bufferline that I have discussed *many times*, if you search for undo tree and offsets in bufferline you will find similar issues. I explained in those issues that offsets in bufferline work by checking if a window is *full height*, and if so it adds an offset if that window has a matching filetype. In your example, your outline window after opening toggleterm is not full height 

<img width="311" alt="image" src="https://user-images.githubusercontent.com/22454918/174735435-e924dc6c-b582-46d1-8076-9577f1785f11.png">

So it is no longer applicable for offsetting as I mentioned in other similar issues in bufferline, the offset logic cannot handle every possible edge case

**Comment by askfiy** [comment]
Ok, I think I understand the reason for this exception.

This may be difficult to solve ..

then i closed it, thanks for your reply
