### ISSUE TITLE
Close only when successful

### ISSUE THREAD

**Issue by justusschock** [akinsho/toggleterm.nvim#265]
Hi, thanks for this very great plugin!

Is there a way to achieve that the terminal is only closed when the process exited with 0 but stays open otherwise?

I have tried the following (which unfortunately didn't work):

```lua
on_exit = function(t, job, exit_code, name)
  if exit_code == 0 then
    t.close()
  end
end,
```

**Comment by akinsho** [comment]
@justusschock can you clarify what command you are trying to run and how you are running it that doesn't work? Can you also clarify that the on exit handler is correctly being called and what the value of the exit code is?

In general, this plugin provides users with the tools to implement this sort of functionality that you might want on your own. I don't specifically know how you might tie things together to get your desired outcome, it will likely involve some trial and error. As mentioned, starting with what commands you are running, how that is behaving is a good first point.

Ultimately my own involvement will only be if there is a bug in the code preventing this working correctly rather than to help figure out how to do this specific thing.

**Comment by akinsho** [comment]
@justusschock close will only close the window not destroy the terminal. You probably want to use `shutdown` instead or something that will actually kill the terminal

**Comment by justusschock** [comment]
Works perfectly, thank you!
