### ISSUE TITLE
Launching terminal with an initial command, like `Terminal:new`

### ISSUE THREAD

**Issue by krshrimali** [akinsho/toggleterm.nvim#298]
Hi, I'm looking to bind running my build file for each project to launching a vertical terminal. How can I do this using toggleterm?

`TermExec` sends the command to the recent terminal. So doesn't really help in this case.

Basically, I want to launch a terminal with a given command every time I hit a keymap. Is it possible using toggleterm?

**Comment by akinsho** [comment]
@krshrimali please don't use the issue tracker as a customer support desk or help centre, it's for reporting bugs i.e. specifically broken things, or suggestion feature requests that you might have time to help implement or have at least thought through implementation yourself.

I'm only one person and maintain several plugins as well as a job and a personal life, I can't help every user with every use case. Please read the docs, please look at other people's configurations.

**Comment by krshrimali** [comment]
> @krshrimali please don't use the issue tracker as a customer support desk or help centre, it's for reporting bugs i.e. specifically broken things, or suggest feature requests that you might have time to help implement or have at least thought through implementation yourself.

Hi Akin! I appreciate and I understand that you can't help with all the issues. However, to call this as a mere attempt to treat as a customer desk or help center, sounded unfair. I understand though, that it wasn't an issue to be raised, I should have asked in some other discord community for neovim users.

Also, you can freely ignore the issue, close it as not to be answered, by creating an issue - no one interferes in your job or your personal life. :)

Thank you!

**Comment by akinsho** [comment]
@krshrimali describing it as

> a customer support desk or help centre

is not intended harshly but simply at face value i.e. this is not an issue with the plugin not working or a request for it to have some new functionality but rather a request for help to make it work a certain way that you would like. "How can I make the plugin do X in my workflow". I get *dozens* of these requests, almost daily or more. I find this sort of question particularly exhausting because I just made and put a tool on the internet, how someone uses it is their own work/adventure/journey not mine. 

As far as just ignoring issues that's not how I work at all, I regularly attend to my issues and check what is valid and what isn't, answer questions or respond to issues. This takes *time* and *energy*. If I just left/ignored issues, many things would get missed and this tool would not continue to be as useful.

An issue on a repo is not (IMO) a zero cost thing that should just be opened, since it will require a maintainers time and attention.

> Also, you can freely ignore the issue, close it as not to be answered, by creating an issue - no one interferes in your job or your personal life. :)

For an active maintainer, the above statement is very far from true.

**Comment by krshrimali** [comment]
> For an active maintainer, the above statement is very far from true.

Well, we diverge on our opinions here, but that's a good part! It's all open-source is about, I believe. I thank you for your contributions, and work.

I can understand what you mean by exhausting, and I'll try to help others wherever I can on this repo once I've dug deeper. Again, don't mind my arguments, wish you the best!

Thank you!
