### ISSUE TITLE
Using mouse within toggleterm

### ISSUE THREAD

**Issue by strogonoff** [akinsho/toggleterm.nvim#316]
I have verified that:

- My terminal application handles mouse input
- Software I run within the terminal (e.g., lazygit) handles mouse input when run directly in terminal
- Nvim itself handles mouse input

However, if lazygit is run within toggleterm within nvim, it does not seem to handle mouse input. I wonder if it is a configuration option or mouse support is not yet implemented?

**Comment by akinsho** [comment]
@strogonoff how mouse input is handled in the terminal in neovim is well outside the scope of this plugin, which simply opens the native terminal inside of specific window layouts. How the terminal behaves e.g. taking mouse input is not controlled or at all handled by this plugin. I just tested out clicking on lazygit inside neovim in toggleterm's floating window, and this worked fine for me.

Please check that you have enabled all the various bits to allow mouse behaviour to work and that this issue does not relate to your neovim version or config. In any event it won't be a problem to raise here since if you search the code base the word mouse isn't mentioned once probably.

**Comment by strogonoff** [comment]
As I wrote, neovim and all other stack components handle mouse input just fine—it is only when toggleterm is involved that mouse input is ignored.

However, I have not yet used native terminal in neovim through any other wrapper.

Since this works for you I assume it is either my config or insufficiently fresh neovim/toggleterm version.

**Comment by akinsho** [comment]
@strogonoff I would suggest running a naked `:terminal` command and then opening `lazygit` and seeing how that behaves this plugin doesn't really is just about opening windows and keeping track of state

**Comment by strogonoff** [comment]
It indeed does not work under plain `:terminal`. Clearly I was mistaken about my neovim handling mouse input, there may be missing configuration. Thanks for the pointer (both figuratively and literally I guess)!
