### ISSUE TITLE
[BUG]: some key combos cause whatever has been typed at the prompt to be deleted

### ISSUE THREAD

**Issue by benwoodward** [akinsho/toggleterm.nvim#320]
So far I have found that ctrl-; and shift-space cause this to happen. It does not happen in neovim, or in a regular iTerm shell prompt—_only_ in `toggleterm`.

![CleanShot 2022-09-19 at 06 02 42](https://user-images.githubusercontent.com/1472981/190926338-c01351c4-cf3e-4d7d-896f-4511429f6b2b.gif)

I have triple-checked that these key-mappings don't exist, and even used `nvim_del_key('t', '<c-;>')` to try to remove them. 

My `toggleterm` config:

```lua
local status_ok, toggleterm = pcall(require, "toggleterm")
if not status_ok then
  return
end
toggleterm.setup({
  size = 10,
  open_mapping = [[<c-\>]],
  shading_factor = 2,
  direction = "float",
  float_opts = {
    border = "curved",
    highlights = {
      border = "Normal",
      background = "Normal",
    },
  },
})


function _G.set_terminal_keymaps()
  local opts = {noremap = true}

  if vim.fn.mapcheck("<Esc>", "t") ~= "" then
    vim.api.nvim_del_keymap("t", "<Esc>")
  end
  vim.api.nvim_buf_set_keymap(0, 't', 'jk', [[<C-\><C-n>]], opts)
end

vim.cmd('autocmd! TermOpen term://* lua set_terminal_keymaps()')
```

My `.zshrc`: https://github.com/benwoodward/dotfiles/blob/666d72ec3486422154651d1e255671e4080d1103/.zshrc

My `neovim` configs: https://github.com/benwoodward/dotfiles/tree/666d72ec3486422154651d1e255671e4080d1103/.config/nvim

**Comment by akinsho** [comment]
@benwoodward so toggleterm does not influence *at all* the way that neovim's builtin terminal works. It also doesn't set any key mappings other than the open mapping. When you say you have verified that this doesn't happen in neovim, did you try opening a terminal the native (non-plugin) way, i.e. `:terminal<CR>`. I just tried this out in neovim and I observe that `<c-;>` does clear the prompt, but *this also happens with a vanilla terminal and is not specific to toggleterm*.

I believe the cause likely relates to https://neovim.discourse.group/t/keymap-c-does-not-work/2254 and is likely due to how *neovim and your terminal emulator* interpret certain key combos. Some key combos are read by neovim as being something other than what you might think.

In any event, as this command is reproducible in a vanilla terminal it is *not a toggleterm issue*

**Comment by benwoodward** [comment]
thanks for the lead @akinsho! I will continue investigating
