### ISSUE TITLE
Neovim 0.8+ and neovide - broken floating terminal

### ISSUE THREAD

**Issue by xbladesub** [akinsho/toggleterm.nvim#325]
I use neovide as neovim gui, just updated to latest neovim version. Can't run lazygit in floating terminal window - it just freezes my neovide instance some reason. Everything works in alacritty for example. Was fine before update. Not sure that it is 100% toggleterm issue

**Comment by akinsho** [comment]
@xbladesub This seems like something to raise with neovide rather than here. If things are working correctly in Alacritty as they are in kitty term for me then I don't think this is something that I'd be expected to fix. I don't know how the terminal interacts with GUIs at all. Also, to be honest, the changes in 0.8 to the terminal relate to the library that is used in neovim core toggleterm doesn't control these sorts of things, that comes from neovim directly

**Comment by akinsho** [comment]
If someone along the chain of debugging feels that this is a toggleterm issue, feel free to re-open it, but it does not sound like one. If running `:terminal<CR>` then running lazygit in neovide results in the same issue then this is definitely not a toggleterm and should be dealt with in that GUI

**Comment by xbladesub** [comment]
> 

running lazygit in separate terminal window works fine (I meant only floating lazygit). I already opened issue in in neovide repo. https://github.com/neovide/neovide/issues/1575#issue-1393353687
