### ISSUE TITLE
Oh My Posh Theme not showing on toggle term

### ISSUE THREAD

**Issue by tykoon787** [akinsho/toggleterm.nvim#341]
Whenever I spawn a terminal instance inside nvim, the terminal does not show up with my custom bash theme. I have, however, seen quite a number of other users using toggle term with their custom themes. I don't know why I it doesn't work. 

**My Normal terminal** 
![image](https://user-images.githubusercontent.com/85307460/200829845-1bfce13c-ca06-4745-848e-ed37677a33c9.png)

**My toogle term** 
![image](https://user-images.githubusercontent.com/85307460/200830059-5a8cfb7e-3592-41d8-8b56-2540f295ae29.png)

**Comment by akinsho** [comment]
@tykoon787 this likely relates to which shell neovim is running. This isn't something that this plugin is setting or interacting with but rather an issue you need to sort out with your neovim config in general as this is almost certainly the case with the native terminal i.e. `:terminal` and not caused by this plugin

**Comment by tykoon787** [comment]
@akinsho
True True. 
Changed the shell I was running from `bash` to `tmux`. Works okay.

**Comment by kristoferjoseph** [comment]
I added `vim.opt.shell = "bash -l"`
to my options so it would source my `~/.profile` when a terminal is launched
