### ISSUE TITLE
When I open ToggleTerm, it shows "zbzbzbzb"

### ISSUE THREAD

**Issue by ggteixeira** [akinsho/toggleterm.nvim#354]
After updating LunarVim, when I open ToggleTerm it shows the string below. Could it possibly be a ToggleTerm bug?

![image](https://user-images.githubusercontent.com/24235344/204549856-0870a688-bc63-4a76-acfc-e03d986ebf65.png)

**Comment by akinsho** [comment]
I haven't made any changes to toggleterm in several weeks and no one else has reported this nor is it something I'm seeing personally so I think it's quite unlikely to be coming from this plugin. If you are able to reproduce this with a minimal init.lua and can definitely show it's coming from toggleterm you can post here but otherwise I'm going to close this out
