### ISSUE TITLE
Can ToggleTerm Respect Nvim Tree Window? 

### ISSUE THREAD

**Issue by DennisTheMenace780** [akinsho/toggleterm.nvim#359]
I have Toggle Term and Nvim Tree set up and what I find happening is that the window for NvimTree can be _above_ Toggle Term, or it can be to the left of Toggle Term if I do a toggle on NvimTree. I have included two image links below to demonstrate that.

I need to figure out a way to get Toggle Term to respect the boundary of the Nvimtree window when I open Toggle Term. Otherwise what happens in the case that Nvimtree is above Toggle Term, if I do a window motion from my main buffer into Toggle Term, and then from Toggle Term to the main buffer, I actually put my cursor on NvimTree because it is directly above Toggle Term.

Edit: I believe that I can figure this out, however I need to be able to specify the dimensions of the terminal window in horizontal mode. When I look for how to do this, it seems that there is only a `size` option, and then from there it's not clear to me how the horizontal width of the terminal is being set. If I can figure out how to set the horizontal width of the terminal, then I think I got this sorted out!

[What I don't want](https://freeimage.host/i/HCPWNqB) arises when I first activate the NvimTree window, and then bring up Toggle Term. 

[What I do want](https://freeimage.host/i/HCPWjsV) arises when I first activate the ToggleTerm window, and then bring up NvimTree.

**Comment by akinsho** [comment]
@DennisTheMenace780 I get this issue and variations of it *a lot* I've also explained in some detail the reasoning for this #97 is one example. I will leave it to you to have read through historical issues.

Apologies in advance because this won't be of much help, but I'm really trying to manage the amount of time I have to contribute to my OSS projects. I'm going to close this as a duplicate, as I think searching for nvim-tree in this repo will bring up a few more previous issues where I've answered in more detail.
