### ISSUE TITLE
What is the expected behavior?

### ISSUE THREAD

**Issue by hacker-DOM** [akinsho/toggleterm.nvim#365]
Disclaimer: I am new to ToggleTerm, it just came with my Astronvim, which I installed yesterday. I am not sure the following is a bug/issue, that's why I'm asking first :-)

Hey folks, it's not 100% clear to me what the expected behavior is. I am using zsh-vi-mode. AFAICT:

- pressing escape should switch to Vim's normal mode (so zsh normal mode would not be accessible (which I'm fine with I guess))
- Nvim's keybindings like <C-w>h should take precedence

Is that the correct understanding? For me, (1) just changes to normal mode _inside zsh_, but not in the terminal itself (e.g., i still cannot go to Command mode by pressing `:`)

(2) also doesn't work - I have no way to leave the terminal except by focusing (selecting) a different buffer with my mouse.

**Comment by akinsho** [comment]
Hi @hacker-DOM,

So these are all good questions but unfortunately not really questions for this plugin but actually questions relating to how neovim's terminal emulator works which I would suggest reading through `:help terminal` for.

This plugin is just a thin wrapper around the native terminal functionality and not actually in control itself of the things you have described. It is essentially a UI plugin that just makes sure the terminal is opened easily and kept track of. I'm going to close this out since it doesn't really relate to this plugin and tbh, although I could get stuck into answering it would take up a lot of my very limited time, sorry. There are answers to this stuff in the help docs and the internet more generally.

**Comment by TieuLongHo** [comment]
@hacker-DOM did you found a way to make it work?

**Comment by hacker-DOM** [comment]
Not yet, no

**Comment by TieuLongHo** [comment]
I found a way to make it work for me somehow. Just add this to your configuration `vim.keymap.set("t", "<esc>", [[<C-\><C-n>]], { noremap = true })
`
and if you want to switch panel with `ESC` just add this one `vim.keymap.set("t", "<esc>", [[<C-\><C-n>][<C-w><C-k>]], { noremap = true })
`

It worked for me

**Comment by magoz** [comment]
I made it work using the `function _G.set_terminal_keymaps()` function as suggested in the [docs](https://github.com/akinsho/toggleterm.nvim#terminal-window-mappings):

```lua
function _G.set_terminal_keymaps()
	-- We use <esc><esc> to be able to use a single <esc> in the terminal Vi mode.
	vim.api.nvim_buf_set_keymap(0, "t", "<esc><esc>", [[<C-\><C-o>:ToggleTerm<CR>]], { noremap = true })
end
```

I've found `<esc><esc>` a better mapping because in this way I can still use the Vi mode on the terminal with `esc`.
