### ISSUE TITLE
Send text to terminal w/o returning

### ISSUE THREAD

**Issue by hacker-DOM** [akinsho/toggleterm.nvim#366]
Hey folks, when I use one of the send text commands (includ. SendVisualSelection) a return seem to be always be appended (the text auto-executes, inside of zsh) Is this expected behavior, and if so, why? :-)

**Comment by akinsho** [comment]
So this functionality was user contributed, tbh I don't use it so no real notion of if this was what the other intended, but I haven't been asked anything about this aspect of its behaviour before, so presumably this is what was intended, or it could be that you are sending wholes lines etc. not sure, but this isn't really phrased as a bug or issue and the original author who wanted this feature seems to have got what they wanted, and I haven't really had complaints in several months since its addition.

FWIW there isn't really a team managing this plugin just me in the spare moments of free time I have between other projects, work and life, so it's probably better to ask questions on Reddit or neovim discourse etc. (issues are welcome for bugs) otherwise please consider raising PRs.

**Comment by hacker-DOM** [comment]
Fair enough, I like opening non-strict issues because it could help others. But it's your project I'll respect your preference
