### ISSUE TITLE
[BUG] Can't switch to new buffer in ranger

### ISSUE THREAD

**Issue by guidiamond** [akinsho/toggleterm.nvim#377]
# Context
I was previously using [vim-floatterm](https://github.com/voldikss/vim-floaterm) but decided to migrate to toggleterm as it has lua support.
I wanted to use ranger (my default file manager) with vim as I used to (through this [wrapper](https://github.com/voldikss/vim-floaterm/blob/master/autoload/floaterm/wrapper/ranger.vim)), but I ran into a problem when trying to adapt this [implementation](https://github.com/akinsho/toggleterm.nvim/issues/66#issuecomment-927042740):

```lua
local ranger = Terminal:new({
  cmd = 'ranger --choosefiles="' .. ranger_tmpfile .. '"',
	hidden = true,
  on_close = function(term)
    local file = io.open(ranger_tmpfile, "r")
    if file~=nil
      then
        vim.cmd("e " .. file:read("*a"))
        -- vim.api.nvim_open_win(fil:read("*a"), true)
        file:close()

        os.remove(ranger_tmpfile)
    end
  end,
})
```
# Problem
When trying to edit a new file through ranger, I expected it to move the current window to the buffer, but that doesn't happen, the buffer gets created but I have to manually switch to it.
In case I use `tabe` instead of `e` the window change works correctly, but I don't want to use tabs.

# Screenshot
![bug-toggleterm](https://user-images.githubusercontent.com/38350062/209738099-87dce031-98bb-4071-8d80-f4c22486087a.png)

**Comment by akinsho** [comment]
@guidiamond floaterm does some "magic" for the user to handle opening files from external terminal programs in vim for the user. In neovim there are commands and tools to do this e.g. neovim-remote. I personally do not think that it is the responsibility of this plugin to do that since this feature exists/existed for neovim and can be configured by the user either using a custom tool such as neovim-remote (created by a neovim maintainer) or using the recently re-added `--remote` command. In either case the best solution in my mind is learning how to use recently re-introduced native functionality like `--remote` etc. rather than this plugin adding 100s of line of scripting to try to do this for the user as I don't have time or desire to maintain that when it can be solved natively with a bit more work as needed by the user.

**Comment by guidiamond** [comment]
That didn't work, for some reason the terminal gets stuck if you use it with remote.
However I was able to find another solution for this in case anyone ever needs it:

```lua
local function feedkeys(keys)
  local key_termcode = vim.api.nvim_replace_termcodes(keys, true, true, true)
  vim.api.nvim_feedkeys(key_termcode, 'n', false)
end

local ranger_tmpfile = vim.fn.tempname()
local ranger = Terminal:new({
  cmd = 'ranger --choosefiles="' .. ranger_tmpfile .. '"',
	hidden = true,
  on_exit = function(term)
    local file = io.open(ranger_tmpfile, "r")
    if file~=nil
      then
        local file_name = file:read("*a")
        file:close()
        os.remove(ranger_tmpfile)
        -- Until edit buffer goes to the correct buffer,
        -- emulate keystrokes to do the same
        vim.cmd("vs " .. file_name)
        feedkeys("<C-w>h")
        feedkeys("<C-w>q")
    end
  end,
})
```
