### ISSUE TITLE
Feature request: hide status column

### ISSUE THREAD

**Issue by Isrothy** [akinsho/toggleterm.nvim#392]
Since neovim 0.9 introduced new feature status column, is it possible to hide status column in toggleterm window?

**Comment by akinsho** [comment]
@Isrothy this shouldn't be done here IMO since it's not like toggleterm is the one setting this value. By default the `statuscolumn = ''` so it must be that a user is adding the statuscolumn themselves whereas it could be set specifically per filetype. Also some users might want to use a custom statuscolumn for their terminal 🤷🏿 (not sure of the value of that but not sure it's worth blocking it either)

I think you should probably create an `ftplugin` file for toggleterm or filetype autocmd and set the statuscolumn to `''`.

**Comment by Isrothy** [comment]
Solved! Thank you for your reply!
