### ISSUE TITLE
Feature: Constant id to send for the terminal with ID matching tabpagenr()

### ISSUE THREAD

**Issue by KohlJary** [akinsho/toggleterm.nvim#393]
I have my toggle term buffers organized by tab page number, which requires me to set some custom commands up in my configuration to be able to toggle the toggleterm buffer associated with the current tab number like so:

command ToggleTermTab :execute tabpagenr().'ToggleTerm'
command ToggleTermSendCurrentLineToTab :execute 'ToggleTermSendCurrentLine '.tabpagenr()

It would simplify things if there were a set value/command I could use in place of this setup to tell the plugin to perform X function on whichever terminal has an ID matching the currently active tab page, without having to configure it myself in my own configuration.

**Comment by akinsho** [comment]
@KohlJary whilst I'm not entirely sure exactly what you're describing it sounds fairly specific to your workflow and what is inconvenient for you which is not necessarily a good basis for adding yet more code to be maintained here.

But as this is OSS if you are willing to clarify your idea and put in the time to build it out I'm happy to look over the PR. I'm personally unlikely to implement this since it's not at all something that I'd have any use for nor could I see this really scaling to a good number of users which is sufficient justification for yet more code IMO

**Comment by KohlJary** [comment]
Yeah I kinda worded that pretty poorly, my apologies. I'll see about implementing it in a fork which should make significantly more sense.
