### ISSUE TITLE
Question: is there a way to open and not toggle?

### ISSUE THREAD

**Issue by szechp** [akinsho/toggleterm.nvim#394]
Hi, 

is there a way to open a terminal, but not toggle it? so if i send the same open command, it stays open? i would need this for a macro and im not sure if this is even possible.

**Comment by akinsho** [comment]
@szechp tbh I don't remember all the functionality this plugin has off hand but it should be documented in the help section or README. Please have a look there. If anyone using this functionality has an answer feel free to post but going to close this out since I don't remember and the best solution is the docs.
