### ISSUE TITLE
[BUG] If you run a endless-loop program in terminal, you cannot interrupt it by <C-c>

### ISSUE THREAD

**Issue by ysl2** [akinsho/toggleterm.nvim#398]
I write a code to test it:

```c
// main.c
#include <stdio.h>

int main()
{
    int i = 1;
    while (i > 0)
    {
        printf("%d", i);
        ++i;
    }
    return 0;
}
```

I compiled it and ran in toggleterm, but cannot interrupt it.

I also tried the external terminal (powershell 7), it can interrupt the program normally.

My minimal config is here:

```lua
require('toggleterm').setup({
  open_mapping = [[<c-\>]],
  direction = 'float',
})
```

Ref1: https://github.com/akinsho/toggleterm.nvim/issues/376
Ref2: https://github.com/akinsho/toggleterm.nvim/issues/174

Update:

1. I switched to linux and use bash as toggleterm beckend, it can interrupt the program.

     So the bug is related to specific terminal, and powershell 7 cannot interrupt c endless-loop program.

2. I rewite the script by python, and both powershell 7 and bash can interrupt.

     So the bug is also related to specific language.

    ```python
    def temp():
        i = 1
        while i >= 0:
            print(i)


    if __name__ == '__main__':
        temp()
    `` `

**Comment by akinsho** [comment]
@ysl2 thanks for raising this issue and debugging things. If as you say this issue is caused by upstream behaviour and in either case what happens within the terminal itself isn't really toggleterm's domain then this is best raised with the neovim team rather than here as this plugin is essentially a UI plugin and doesn't control the terminal's actual behaviour
