### ISSUE TITLE
Terminal becomes vertical when deleting file in buffer

### ISSUE THREAD

**Issue by Raagh** [akinsho/toggleterm.nvim#400]
Hi , I have weird case that maybe you can help me fix. 

I am using toggleterm and nvim-tree together.

What happens. 

1. Open a file
2. Open toggleterm as horizontal
3. Open nvim-tree
4. Delete file which is open
5. Toggleterm takes the full screen
6. Open a new file
7. Toggleterm becomes vertical split

What I would expect

1. Open a file
2. Open toggleterm as horizontal
3. Open nvim-tree
4. Delete file which is open
5. Toggleterm takes the full screen (it would be even better if nvim-tree would create a new empty buffer I guess)
6. Open a new file
7. Toggleterm goes back to horizontal

![nvim-2023-02-21-12-03-58](https://user-images.githubusercontent.com/8405459/220329153-8bdd6db6-ed8d-484e-8cd4-f1211d3796f9.gif)

**Comment by akinsho** [comment]
Hi @Raagh 

So unfortunately what you describe is just the way that vim works. The terminal buffer is just a regular buffer and so is its window. What you were saying is what will happen to any window if you do the sequence of actions you've done there there isn't really an easy way to solve this short of creating some sort of window watcher that checks for the window being in the wrong position and then tries to replace it. Many issues like this have been raised in this plugin for a while but to my mind this all comes down to how neovim behaves.

I'm not against someone contributing a solution to this and building this window handler listener thing, but it's a lot of time and effort that I don't want to spend personally. The easiest and best solution most people choose, is to find a plugin that properly deletes a buffer without messing up your windows since it's the fact that your window got messed up that caused this issue
