### ISSUE TITLE
CTRL-W = (aka Make all windows the same height & width) won't work

### ISSUE THREAD

**Issue by horta** [akinsho/toggleterm.nvim#407]
https://asciinema.org/a/564804

**Comment by akinsho** [comment]
@horta this is essentially expected behaviour because toggleterm sets the width or height of  window based on a user's configuration or their settings *and fixes* the window height/width so attempts to change it without going through toggleterm's mechanisms largely won't work. You can use the size=<value> argument or set your preferred values in your config.

**Comment by horta** [comment]
I see. That would be like a floating panel coming from the side. I wonder if most people like that way.

Anyway, great plugin. I love it =)
