### ISSUE TITLE
[BUG] Can't send visual lines to terminal using keymap

### ISSUE THREAD

**Issue by patata3000** [akinsho/toggleterm.nvim#415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Disclaimer: This may be due to my inexperience with lua in nvim.

I'm trying to create a keymap that's calling a lua function. In this function, I want to do some stuff with some lua code then send visual lines. This snippet doesn't work:

```lua
-- Create custom terminal
local Terminal = require('toggleterm.terminal').Terminal
local jupyter = Terminal:new({
  count = 8,
  cmd = "jupyter console",
  hidden = true,
  start_in_insert = false
})

-- Set keymap
local function start_and_send_visual_line_python()
  -- Do stuff here in lua, then run:
  vim.api.nvim_command(vim.fn.line("v") .. "," .. vim.fn.line(".") .. "ToggleTermSendVisualLines " .. jupyter.id)
end
vim.keymap.set({ "v" }, ",so", start_and_send_visual_line_python,
  { desc = "Send visual lines to terminal", silent = false, noremap = true })
```

It seems that it will send the previously selected lines to the terminal.

### Expected Behavior

I'm expecting this keymap to send the currently visually selected lines to my jupyter terminal.

### Steps To Reproduce

- Open the jupyter terminal (id: 8 in my case)
- Select some python lines (it's independent from python)
- Use the defined keymap (`,so` in this case)

### Environment

```Markdown
- OS: archlinux
- neovim version: 0.8
- Shell: zsh
```

**Comment by akinsho** [comment]
@patata3000 this issue is almost entirely a usage/configuration type issue rather than a bug per se. Tbh the sending lines to the terminal functionality was contributed by a series of users who really wanted this functionality and use it. I personally do not use it at all and so cannot offer any advice here (any onlooker can feel free to comment). But since isn't something with the plugin that needs fixing but more of a "how can I do x in my config?" I'm going to close this out since this isn't the sort of issue I generally can afford to tackle (since these are very numerous and time consuming).

**Comment by patata3000** [comment]
Ok thanks anyway. :)
