### ISSUE TITLE
Terminal colors different

### ISSUE THREAD

**Issue by kaykhan** [akinsho/toggleterm.nvim#426]
Hi

When i toggle terminal in neovim using this plugin why are the colours so significantly different compared to opening a terminal normally. See the screenshot for comparison

Top is terminal toggled in nvim
Bottom is normal terminal

![image](https://user-images.githubusercontent.com/5202527/230766988-92c8d71b-b293-4665-915e-2ad56b7bcb96.png)

**Comment by akinsho** [comment]
@kaykhan I assume you are not talking about the terminal shading because this is addressed right at the start in the README and will assume you are describing other terminal colors like your prompt. This is not controlled by this plugin neovim has the concept of terminal colors and colorscheme authors can tweak or change this. Also things like tmux and colors in neovim can affect this.

In short there are many things that can be causing this, none of which relate directly to any functionality of this plugin

**Comment by kaykhan** [comment]
Ok I'm not sure if this issue is the shading you mentioned or something else with tmux/nvim.

Do you have any idea on what I should check ?

**Comment by akinsho** [comment]
@kaykhan you haven't clarified what aspect of the picture is the problem, what colours are wrong, the shading of the terminal or the colours of the prompt etc

**Comment by kaykhan** [comment]
> @kaykhan you haven't clarified what aspect of the picture is the problem, what colours are wrong, the shading of the terminal or the colours of the prompt etc

right, ah i think its called the prompt
![image](https://user-images.githubusercontent.com/5202527/230776068-fbb576be-2ab7-4a60-9f02-37c7e2869cae.png)

**Comment by kaykhan** [comment]
Okay i fixed the issues that were displayed in `:check` surrounding colors and now it reports

```
  - INFO: $TERM_PROGRAM='tmux'
  - INFO: $COLORTERM='truecolor'
```

![image](https://user-images.githubusercontent.com/5202527/230776849-2b6fe30d-c2d1-436c-a3a9-aa4953e25945.png)

so im not sure its an issue with tmux anymore.

**Comment by akinsho** [comment]
@kaykhan the colour of your prompt is definitely not something this plugin influences as just using the raw terminal command probably triggers the same behaviour. I'm not sure exactly where you would look but the issue won't be with this plugin
