### ISSUE TITLE
[BUG] New terminal opened does not respect current terminal direction

### ISSUE THREAD

**Issue by Bekaboo** [akinsho/toggleterm.nvim#428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Toggleterm.nvim has a great feature that we can open terminals "side by side" when the direction is `horizontal` or `vertical`; when current direction is `horizontal`, new terminals are opened to the right (vertically split old window) and when current directions is `vertical`, new terminals are opened below (horizontally split old window).

However, if a terminal is originally in `horizontal` layout and toggled with `:ToggleTerm direction=vertical`, when a new terminal opens by the side of the old terminal, the window is still vertically split, which is not desired.

### Expected Behavior

When a new terminal is opened by the side of the current terminal, it should split the window according to current direction/layout of the current terminal.

### Steps To Reproduce

1. Install toggleterm.nvim and use the default config
2. Enter nvim
3. `:ToggleTerm`, the terminal should be toggled with `direction=horizontal` by default
4. Enter normal mode
5. `:ToggleTerm` to hide the terminal
6. `:ToggleTerm direction=vertical`
7. Enter normal mode
8. `:2Toggleterm` to open a new terminal
9. The new terminal is opened to the right of the old terminal instead of below the old terminal.

### Environment

```Markdown
- OS: `Linux 6.2.10-arch1-1`
- neovim version: `NVIM v0.10.0-dev-39+gaab95ec67e`
- Shell: Bash
```

### Anything else?

Thanks for all your work on this plugin!

_No response_

**Comment by akinsho** [comment]
Hi @Bekaboo, I thought for sure there was an open issue covering this but couldn't find one but this has been touched on in some way several times.

This issue essentially comes down to how much a window manager plugin I want to build/maintain vs just a terminal plugin. Generally speaking managing window layouts and orientations isn't/wasn't a motivating goal for this plugin.

The horizontal/vertical "tiling" behaviour was kind of straight forward to achieve but opened the door to this exact kind of request/issue but solving that problem is AFAIK harder and tbh not particularly appealing to me.

The difficulty here is say in the example you have a user has opened two vertical terminals. They then close one and try to re-open it with a horizontal direction, what should happen? should there be a full width terminal split on the bottom now? what happens when they split without a direction next? should it add another horizontal split or respect the global config direction of vertical?

Doing all this is certainly possible but honestly this is pretty different to how I use the plugin and what I intended really. The general idea is a user wants to have a terminal in the bottom or the right and these are pretty stable preferences. They aren't looking to change them on the fly or create a complex layout of terminals.

None of this is to say that I'm anti this feature, if someone comes by sees this and wants to tackle it their absolutely welcome to but, it would be several days of my time and possibly weeks of follow up bugs or quirks for a feature that I honestly don't think that I need. A lot of toggleterm was inspired by things like Intellij and other GUI editors and using those it's always been more than enough for me to just have things on the bottom and split from there.

**Comment by Bekaboo** [comment]
Thanks for your detailed explaination on this!
