### ISSUE TITLE
[BUG] nvim will scroll to the cursor position after closing the terminal.

### ISSUE THREAD

**Issue by ruinb0w** [akinsho/toggleterm.nvim#431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://user-images.githubusercontent.com/12596011/233784075-5c9b02ff-449c-4c20-86f5-2aec87b8a4f1.mp4

### Expected Behavior

keep nvim position

### Steps To Reproduce

1. move cursor to any position
2. open terminal
3. close terminal
4. the top of nvim will move to cursor position

### Environment

```Markdown
- OS: macos 13.3.1
- neovim version: 0.9
- Shell: zsh
- Terminal: hyper
```

**Comment by akinsho** [comment]
@ruinb0w I've just tested this out and am unable to reproduce this issue. Can you please retry this test with a *minimal init.lua* that doesn not load your other plugins and just loads this plugin. If you verify that it happens with a minimal `init.lua` then please post it and the steps to reproduce this issue here

**Comment by ruinb0w** [comment]
caused by nvim config
