### ISSUE TITLE
[BUG] terminal doesn't stay in insert mode when clicked into with a mouse

### ISSUE THREAD

**Issue by airtonix** [akinsho/toggleterm.nvim#439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

👋🏻  Mouse Using Heretic Here 🤝 👍🏻 

```lua
 {
    -- toggleterm.nvim
    "akinsho/toggleterm.nvim",
    opts = {
      hide_numbers = true,
      -- these two options will force the terminal to always be in insert mode
      start_in_insert = true,
      persist_mode = true,
    },
  },
```

1. Have a file open.
2. be in normal mode.
1. `:ToggleTerm`
3. Viz: terminal is in `insert` mode
4. click in the file from `.1`
5. click back into the terminal from `.3`
6. Viz: terminal is not in `insert` mode.

### Expected Behavior

Always be `insert` mode.

### Steps To Reproduce

see above.

### Environment

```Markdown
- OS: anything
- neovim version: anything
- Shell: anthing.
```

**Comment by akinsho** [comment]
Hi @airtonix,

Tbh I have absolutely no idea what nvim does or how it deals with mouse clicks at all. How are they the same how are they different where do I even start to look to figure out why the behaviour might be different. This could be easy or hard to fix but I'll be completely honest I really am not super inclined to spend an evening digging into mouse stuff in neovim unfortunately.

If someone who knows about this wants to dig in I'd appreciate the help otherwise I don't think this is something I'm likely to get the motivation to dig into myself.

**Comment by akinsho** [comment]
It's important to note that using the keyboard with the window keymappings to use `wincmd (H|J|K|L)` works as expected. Maybe something similar needs to be done i.e. remapping the mouse click focus behaviour 🤷🏾‍♂️

**Comment by airtonix** [comment]
I think some advice around autocmds and BufEnter would be helpful perhaps?

**Comment by akinsho** [comment]
@airtonix `:help :terminal` has information on how to setup insert mode which recommends using
```vim
autocmd TermOpen * startinsert
```
There's not some extra different or better advice I can give since this plugin is already essentially doing this on the users behalf when they choose to start in insert. In your case maybe the thing to do is turn off persisting the mode since I don't think reliably persisting the mode will not work with mouse clicking without someone going down the rabbit hole to fix or investigate that.

I recommend disabling `persist_mode` in your case which will essentially add the above autocommand and not try to track the previous mode.

I'll close this out now. If some other mouse user wants to dig into the logic of how mode works with mouse clicks or what happens when the mouse changes focus feel free to raise a PR

**Comment by airtonix** [comment]
none of that works actually. 

this does though: 

```
vim.api.nvim_command('augroup terminal_setup | au!')
vim.api.nvim_command('autocmd TermOpen * nnoremap <buffer><LeftRelease> <LeftRelease>i')
vim.api.nvim_command('augroup end')
```

and this should be documented on toggleterms README
