### ISSUE TITLE
[BUG] Sending texts to terminal ruins the side-by-side layout

### ISSUE THREAD

**Issue by Bekaboo** [akinsho/toggleterm.nvim#447]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If two terminals are opened side by side, sending texts to one of the them will ruin the side-by-side layout, e.g. only the destination terminal will be toggled on.

### Expected Behavior

If two terminals are opened side by side, sending texts to one of them toggles both terminals on, keeping the layout.

### Steps To Reproduce

1. Install toggleterm.nvim on nvim
2. `:Toggleterm`
3. Enter normal mode
4. `:2Toggleterm`
5. Enter normal mode
6. Toggle off the terminals
7. Select some texts in normal buffer in visual mode, `:'<,'>ToggleTermSendVisualSelection`
8. Only terminal 1 is opened

### Environment

```Markdown
- OS: Linux 6.3.6-arch1-1
- neovim version: NVIM v0.10.0-dev-493+gc53953b400
- Shell: bash
```

**Comment by akinsho** [comment]
Hi @Bekaboo,

So I'm not sure that I think this is actually a bug, someone else contributed the idea of terminal view a while ago which is the idea of opening and closing whatever was opened e.g. if there were 2 terminal open the two, but if you use the visual selection commands then IMO you are trying to operate on only one terminal so only one terminal should be opened.

I personally don't use any of the REPL type functionality (and frankly regret having accepted the contribution since it has ended up being a costly feature creep, with constant requests for new features + issues). All that being said I think if I wanted to send something to a terminal I would expect only that terminal to open not say the 3 I previously had open I think that's kind of unhelpful/unintuitive but as is always the case with most nvim plugins I'm sure different people with different workflows won't always agree.

**Comment by Bekaboo** [comment]
Oh OK, actually I opened this issue in case it is an unexpected behavior, closing it now.
