### ISSUE TITLE
[BUG] toggle term only setting keymap to insert mode

### ISSUE THREAD

**Issue by hemanth-kotagiri** [akinsho/toggleterm.nvim#451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When `[[<C-\>]]` is triggered, its not working in normal mode. Checking the list of key maps using Telescope, turns out the `  open_mapping = [[<C-\>]],`  is only setting it for insert mode.

### Expected Behavior

open_mapping should create the key map for normal mode, as well as insert mode.

config: 
```lua
toggleterm.setup({
  open_mapping = [[<C-\>]],
	size = 20,
	hide_numbers = true,
	shade_filetypes = {},
	shade_terminals = true,
	shading_factor = 2,
	start_in_insert = true,
	insert_mappings = true,
        terminal_mappings = true,
	persist_size = true,
	direction = "float",
	close_on_exit = true,
	shell = vim.o.shell,
	float_opts = {
            border = "curved",
            winblend = 0,
            highlights = {
                border = "Normal",
                background = "Normal",
            },
        },
})
```

### Steps To Reproduce

1. In Normal Mode, press the keybind specified and it doesn't work.
2. In Insert Mode, press the keybind and it works.

### Environment

```Markdown
- OS: arch
- neovim version: NVIM v0.10.0-dev-606+g628f6cce8
- Shell: zsh
```

**Comment by akinsho** [comment]
Hi @hemanth-kotagiri,

This issue sounds about certain to be a configuration issue since this is one of the key behaviours of this plugin that has existed unchanged for at least a year if not longer. Can you please confirm that you have tested in a completely minimal environment as I definitely can't reproduce this

**Comment by hemanth-kotagiri** [comment]
Hey there @akinsho. Yes, I did comment out all the other configuration files that I have in my config, and tried sourcing only Toggle Term - still the same behavior is observed. I tried `:messages` to see if there's any issues after sourcing just toggle term config, but still, I see nothing.

**Comment by akinsho** [comment]
@hemanth-kotagiri rather than commenting out config and things like since I find that sort of method to always leave some stone unturned I strongly recommend running neovim specifically *with a minimal init.lua* which means something like `nvim -u ./path/to/minimal/init.lua` that file should only load toggleterm and then run it with that config.

I just tried this out on a minimal config locally that used the following content and it worked correctly.

```lua
local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
vim.opt.runtimepath:prepend(lazypath)
----------------------------------------------------------------------------- }}}1
require('lazy').setup({
  { 'akinsho/toggleterm.nvim' },
}, {
  dev = {
    path = '~/projects/personal/',
    patterns = { 'akinsho' },
  },
})

vim.opt.termguicolors = true

require('toggleterm').setup({
  open_mapping = [[<C-\>]],
  size = 20,
  hide_numbers = true,
  shade_filetypes = {},
  shade_terminals = true,
  shading_factor = 2,
  start_in_insert = true,
  insert_mappings = true,
  terminal_mappings = true,
  persist_size = true,
  direction = 'float',
  close_on_exit = true,
  shell = vim.o.shell,
  float_opts = {
    border = 'curved',
    winblend = 0,
    highlights = {
      border = 'Normal',
      background = 'Normal',
    },
  },
})
```

Also please make sure you are running the absolute latest commit. I think this is a configuration issue and unfortunately I really don't dig into these since everyone's config is different and i'd spend all my FOSS time debugging configs if I did that.

**Comment by tudorjnu** [comment]
I have the same problem over here. The keymap is set and if I am searching for it, it will get triggered. The mapping does not work though. Switching the mapping to a different one works.

**Comment by hemanthlouvir** [comment]
@tudorjnu I resolved the issue by checking all the key maps that I have in my config. For me, the issue was that a same mapping was used for one of tmux plugin(I copy pasted the config for it and it had keymaps), and I was sourcing the tmux plugin file after the toggle term file. You might try checking the same.

**Comment by hemanth-kotagiri** [comment]
@tudorjnu I resolved the issue by checking all the key maps that I have in my config. For me, the issue was that a same mapping was used for one of tmux plugin(I copy pasted the config for it and it had keymaps), and I was sourcing the tmux plugin file after the toggle term file. You might try checking the same

**Comment by davidarny** [comment]
@tudorjnu i'm having same issue with tmux. Have you found a solution?

**Comment by tudorjnu** [comment]
@davidarny no, sorry. I gave up and went for [[<C-t>]].

**Comment by hemanth-kotagiri** [comment]
Hey @tudorjnu , @davidarny . Yes I found the issue, sorry I haven't updated here. As the author mentioned, it was conflicting with one other keymap - in my case, it was a default keymap that came from a different plugin. I think it was tmux navigator.

Hope it helps!
