### ISSUE TITLE
Feature Request: Terminal:open provides an opts param with an origin_window field so that invoker can specify the window getting back when terminal is closed

### ISSUE THREAD

**Issue by skyf0cker** [akinsho/toggleterm.nvim#475]
In the current implementation, in the Terminal:open function, the previous window before opening the terminal is stored in the origin_window variable using nvim_get_current_win. After the terminal is closed, it jumps back to the origin_window. 
https://github.com/akinsho/toggleterm.nvim/blob/12cba0a1967b4f3f31903484dec72a6100dcf515/lua/toggleterm/terminal.lua#L471
This approach works fine when the user directly creates a terminal from the currently active window, such as when coding. However, there is a problem with some plugins based on toggleterm, such as [toggletask.nvim](https://github.com/jedrzejboczar/toggletasks.nvim), which is a plugin similar to the VSCode task runner. It opens a terminal to execute commands using the telescope.nvim picker. In this case, the origin_window will be set to the win_id of the telescope picker, and after the task is finished, it attempts to jump to the telescope window. However, this window is temporary, and this method of jumping cannot reach the desired window that was active before triggering the telescope picker.

Based on the above description, I am wondering if the Terminal:open function in toggleterm can be modified to specify the origin_window. This would allow plugins dependent on toggleterm to further optimize their usage.

Finally, toggleterm is a great plugin and I hope you could consider adding this feature. If possible, I would also be happy to assist with some simple development.

**Comment by skyf0cker** [comment]
@akinsho Thanks for your time and hope for your reply. :)

**Comment by akinsho** [comment]
Hi @skyf0cker,

I don't have much/any time on my hand for the influx of feature requests I'm currently getting on my projects. Tbh whilst the request is understandable this is quite specific to the use case of people using that plugin so to my mind not high priority by default.

I don't love the idea of making things more complex to match increasingly more complex use cases. This plugin has always been fairly straightforward to manage because it doesn't try to handle every single use case.

I'd accept a PR that made sure that setting origin window always ignored floating windows since that seems like a generally useful addition but I definitely don't have the time for this myself. Please feel free to raise a PR.

If you think you won't have time or the desire to do that then please feel free to close this issue 🙏🏾
