### ISSUE TITLE
Is it possible to allow users to set the size of the toggleterm to half of the current window and can change the size automatically, like split?

### ISSUE THREAD

**Issue by nullptr-yxw** [akinsho/toggleterm.nvim#484]
The `ctrl+w =` cannot work well with the window of toggleterm, so it's a bit difficult to create a autocmd to change the size of the window automatically when the total size changes, just like splitting the window by `split` .
So is it possible to allow the size to be a float, just like `size = 0.5` to split the window by a rate and can automatically change the window size?

https://github.com/akinsho/toggleterm.nvim/assets/96286337/4c805fda-b906-4bb9-ad37-382bf4e98cf8

↑The size can change automatically when splitting the window by `vsplit`

**Comment by akinsho** [comment]
@nullptr-yxw you can set the size of the window to use a function and do whatever logic you'd like to determine whatever size of window you want. I probably am not going to do anything specific for this use case since the main intention is that a user sets a general size ahead of time or they use a function to do it dynamically

**Comment by nullptr-yxw** [comment]
> @nullptr-yxw you can set the size of the window to use a function and do whatever logic you'd like to determine whatever size of window you want. I probably am not going to do anything specific for this use case since the main intention is that a user sets a general size ahead of time or they use a function to do it dynamically

Actually I meant that it might be a bit difficult to write an autocmd to change the size of the toggleterm window when the total size has been changed, because `ctrl+w =`cannot work with the toggleterm window

**Comment by akinsho** [comment]
@nullptr-yxw I don't entirely think I follow but it doesn't sound like one of the use cases this plugin was originally designed for. To clarify it isn't designed for 100% flexibility or to match every use case. It's very specifically designed in a constrained way i.e. you set a general size for the window which it should remain at consistently. Or it changes due to x function. I think from my perspective this is enough. Try to meet every use case only makes this plugin more complex and less desirable to continue to maintain.

I think aesthetically I don't expect or want this plugin to suddenly resize from the fixed height or width because the window changed. I specifically want it to be a consistent height and that's the default behaviour I had in mind when building this at the beginning
