### ISSUE TITLE
[BUG] Cursor hides when scrolling down

### ISSUE THREAD

**Issue by piotr-marendowski** [akinsho/toggleterm.nvim#511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When normally scrolling down in toggleterm cursor hides and then reappears when scrolling action is over. Same behavior on the minimal config. Neovim's default terminal doesn't have this issue. Both [fff](https://github.com/dylanaraps/fff) and [lazygit](https://github.com/jesseduffield/lazygit) are lagging. Same with bash.

### Expected Behavior

To scroll normally like everywhere else.

### Steps To Reproduce

1. Open a TUI program in toggleterm.
2. Try to scroll down.
3. See this issue.

### Environment

```Markdown
- OS: Arch Linux 6.5.8-arch1-1 x86_64
- neovim version: 0.9.4
- Shell: ZSH
```

### Anything else?

https://github.com/akinsho/toggleterm.nvim/assets/37738748/4e958dca-b15e-448f-a2c0-8702a8123111

**Comment by akinsho** [comment]
@piotr-marendowski there is no code is this plugin to mess with a user's cursor at all. I really can't speak for the behaviour of TUI apps inside neovim vs outside or anything. Only that this plugin doesn't have logic like this. Lazygit is the only of your examples I use and it just highlights the cursor it's own way *outside of neovim as well* this tends to be something that TUI frameworks handle themselves.

If you mean that you can move the cursor separate to the TUI app, then this is because the TUI app *has focus and is in control of the cursor* you could use whatever your terminal mapping to enter normal mode is to change this if you want but essentially this plugin doesn't steal or colour the cursor
