### ISSUE TITLE
[BUG] weird space at the left of the terminal

### ISSUE THREAD

**Issue by diegoulloao** [akinsho/toggleterm.nvim#527]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm seeing a black space at the left of the terminal.

### Expected Behavior

Match the same terminal background.

### Steps To Reproduce

- Just using gruvbox theme: https://github.com/ellisonleao/gruvbox.nvim

### Environment

```Markdown
- OS: macOs Sonoma 14.2.1
- neovim version: 0.9.4
- Shell: zsh / iterm 3.4.22
```

### Anything else?

<img width="1440" alt="Screenshot 4" src="https://github.com/akinsho/toggleterm.nvim/assets/45423661/8134ee4d-0160-4915-9eca-b5e1f16ebf72">

```lua
-- custom setup
toggleterm.setup({
  direction = "float", -- float|horizontal|vertical|tab
  float_opts = {
    border = "curved", -- single|double|curved
    -- winblend = 5, -- transparency, recommended: 5
  },
  size = 20,
  persist_mode = true,
  highlights = {
    Normal = { link = "ToogleTermNormal" },
    NormalFloat = { link = "ToogleTermNormalFloat" },
    FloatBorder = { link = "ToggleTermFloatBorder" },
  },
})

-- highlights
vim.cmd([[ hi ToogleTermNormal guibg=#32302f ]])
vim.cmd([[ hi ToggleTermFloatBorder guibg=#32302f guifg=#32302f ]])
vim.cmd([[ hi ToogleTermNormalFloat guibg=#32302f ]])
```

**Comment by akinsho** [comment]
@diegoulloao it appears you've misspelled the highlight groups please have a close look as this might explain the issue. The area seems to be the `SignColumn` which you can also highlight

**Comment by diegoulloao** [comment]
Actually is not.
Is happening for other colorschemes too.

<img width="686" alt="Screenshot 3" src="https://github.com/akinsho/toggleterm.nvim/assets/45423661/430e79ff-503a-43f8-978c-1a2a9ed9cb1f">

**Comment by akinsho** [comment]
@diegoulloao so as I mentioned, you have misspelt the names of the highlight groups so they are probably getting assigned incorrectly to something else which makes them appear different to the sign column which you are not trying to highlight, but I've left as it originally is. This is almost certainly a configuration issue rather than a bug in the plugin. I'm sorry but especially given this time of year. I don't really have the time to help you debug this. I strongly recommend you have a close look at the names of the highlight groups cuz they are wrong and try fixing it. Hopefully that fixes it, but otherwise I'm pretty sure that this is not a bug since I tried on different machines and it doesn't reproduce. If you manage to narrow it down to a specific minimal configuration that causes this issue without any extra plugins and no colour scheme influence then please raise the issue again.

**Comment by diegoulloao** [comment]
> @diegoulloao so as I mentioned, you have misspelt the names of the highlight groups so they are probably getting assigned incorrectly to something else which makes them appear different to the sign column which you are not trying to highlight, but I've left as it originally is. This is almost certainly a configuration issue rather than a bug in the plugin. I'm sorry but especially given this time of year. I don't really have the time to help you debug this. I strongly recommend you have a close look at the names of the highlight groups cuz they are wrong and try fixing it. Hopefully that fixes it, but otherwise I'm pretty sure that this is not a bug since I tried on different machines and it doesn't reproduce. If you manage to narrow it down to a specific minimal configuration that causes this issue without any extra plugins and no colour scheme influence then please raise the issue again.

I understand, thanks for your reply.

Just FYI, the problem persist even using the neovim built-in themes with all plugins disabled. No highlighted groups are active. Weird...

Thanks!

**Comment by diegoulloao** [comment]
Ok, I figured out, is the `signcolumn = "yes"`. I'm searching how to disable it just for toggleterm buffers (I'm using gitsigns too).

**Comment by diegoulloao** [comment]
this worked:
```lua
{
  -- config
  on_create = function()
    vim.cmd([[ setlocal signcolumn=no ]])
  end,
}
```
