### ISSUE TITLE
Please check instructions

### ISSUE THREAD

**Issue by raffaem** [akinsho/toggleterm.nvim#543]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Please check if the instructions I wrote here are correct: https://github.com/akinsho/toggleterm.nvim/wiki/Per-file-type-shell

### Expected Behavior

See above

### Steps To Reproduce

See above

### Environment

```Markdown
- OS:
- neovim version:
- Shell:
```

**Comment by akinsho** [comment]
@raffaem I don't use any of those languages so I haven't a clue about if there are custom shells to use for those languages 🤷🏾‍♂️ since it's a public wiki if someone wants to change your submission they can. Hopefully you added those because you have tried them. If you haven't actually tried those examples I recommend that you don't add them as you might just confuse someone else

**Comment by raffaem** [comment]
Of course I tested them, but my main question is whether my "understanding" on how the `shell` function is called (first within the code buffer, then within the terminal) was correct! :)
