### ISSUE TITLE
Add vim help documentation

### ISSUE THREAD

**Issue by fedepujol** [akinsho/toggleterm.nvim#57]
It'll be really helpful to have the help documentation (help-tags? Don't know how is it call) for Neovim. Right now I've to come to github and search if what i've want to do is possible. (awesome plugin by the way!)

I could help if you need a hand!

**Comment by akinsho** [comment]
@fedepujol it's a pretty tedious thing to have to manually curate help docs as well as the README in markdown. I maintain 3+ plugins so it's quite a lot of work (for me anyway).

If you or anyone else wants to contribute I'd be happy to have the help. I'm definitely all for it but if it comes down to me doing it tbh it'll be a while since I don't really have the time for that atm.

**Comment by akinsho** [comment]
This is now done using an automated workflow
