### ISSUE TITLE
Track whether in insert mode or not during toggle

### ISSUE THREAD

**Issue by kdheepak** [akinsho/toggleterm.nvim#76]
Hi, thanks for making this plugin! It is awesome!

I like the `start_in_insert = true` feature a lot. However, sometimes (for example, when I am looking at output of a lot of tests), I use `C-\ C-n` to exit insert mode and scroll up, and toggle to get to the test file in question. However, if I want to refer to the test output again, now when I toggle back to the terminal it enters insert mode and goes back to the terminal input and I have to scroll back again. 

It would be nice if the plugin can track whether the user is in insert mode or not and choose _not_ to enter insert mode if a user has `C-\ C-n` in the terminal. 

One way I think this could be achieved is by using autocommands that work only in the terminal. Thoughts?

**Comment by akinsho** [comment]
Hi @kdheepak,

Thanks for the kind words, much appreciated 🙏🏿 .
So persisting state so far has been a bit of a nightmare, probably the because the first implementation was aimed at one specific contributors use case and hasn't scaled well. I'm generally wary about adding more complexity to this plugin. The initial idea was quite simple but the scope has crept a lot.

I think doing this well would mean adding an internal state object to each terminal and tracking the input state of each terminal and saving it and re-applying it on open or `TermEnter`. It would somehow have to override the `start_in insert` as well or add a new options since that option specifically means that it always starts in insert rather than sometimes not since some users will definitely not want that.

Tbh it's not a huge amount of work but not a small amount either, I'd be happy to help guide a PR but will probably not have the time myself to do this for quite a while (if at all, since I'd rather avoid more state if possible)
