### ISSUE TITLE
Feature Idea: dynamic switch of direction for open terminal ?

### ISSUE THREAD

**Issue by kiuKisas** [akinsho/toggleterm.nvim#81]
In can be nice to be able to switch direction of already opened terminal.
E.g: if you launch a server in a terminal, you would want to have it in `float` or `window` direction most of the time, but when it's debug time, it's nice to have it in `vertical` or `horizontal`

**Comment by akinsho** [comment]
@kiuKisas there was a big (and much appreciated effort by @zeertzjq) in #71 to allow dynamic window switching of closed terminals.

Tbh I think we are beginning to stray into window manager territory with all of this logic which is not very simple. I don't think it's a bad use case, but I think it's all making this plugin more complex than it needs to be. For my own part I'm not really sure how we'd achieve this for things like horizontal and vertical splits, you could move the splits hopefully without breaking things but how we'd then keep track of the new layout of each window as they are changing dynamically is beyond me.

I'll leave this open if someone else knows and wants to take a crack at implementing this, but I personally don't know how, and am a little wary of straying more and more into this territory since I feel like it'll invite more future requests for even more complex window behaviour.

**Comment by akinsho** [comment]
So I'm going to close this out since this is "kind of" available in that if you close a terminal and re-open it with a direction, it will now re-open in the new direction. It can't happen on the fly and tbh I'm not interested in going down that very involved rabbit hole. No one else including the OP has stepped up to add this, so in the interest of avoiding issues open for years I'm going to close this out. If someone stumbles on this in the future and wants to contribute it, please do.
