### ISSUE TITLE
[Bug] Number column bug with direction=window

### ISSUE THREAD

**Issue by G-Rowell** [akinsho/toggleterm.nvim#84]
Hi all, 
firstly, a big thanks for this @akinsho :heart: 

I think there may be a bug with `:ToggleTerm direction=window` & with the `hide_numbers = true` setting.

it doesn't seem to respect/restore the line numbers when `:ToggleTerm` is run again to 'hide' the window term.

I did just replicate this on a reasonably minimal install, but maybe I still have made a mistake somewhere?

If you can guide me on what to fix, I'm happy to fix it and make a PR :smile: 

Thanks!

**Comment by akinsho** [comment]
Hi @G-Rowell 👍🏿,

There's almost certainly quite a few bugs with the window layout, I added it largely as an afterthought and almost never use it. It's also one of the messiest layouts because it depends on re-using the window that the user's buffer was in, so things like ensuring the window options like `number` are set and reset properly is a pain because unlike other layouts we'd have to check the options on `BufEnter` and `BufLeave`.

This is where the window layout is created, which basically just creates a buffer if the terminal is new or otherwise sets the window options

https://github.com/akinsho/nvim-toggleterm.lua/blob/775012662eb2070e44b294d43938fa2625a9c836/lua/toggleterm/ui.lua#L264

The line below is where the options are set, but this only happens when the window is created which is basically only once for the window layout since the user's window probably remains open for the whole session unless they open a split then close the initial window or something

https://github.com/akinsho/nvim-toggleterm.lua/blob/775012662eb2070e44b294d43938fa2625a9c836/lua/toggleterm/ui.lua#L114

I think the solutions would be setting an autocommand somewhere where if a person leaves the window of a terminal which has a mode of layout of `window` then we reset the window back to the global value, not sure if there is a `vim.o.number` if not it might need to be saved on enter.

A PR would be great, this month and the next are quite busy for me, so I probably won't have too much time to work on this and my other plugins except for little bits here and there. Happy to help with any more advice or guidance, though.

**Comment by G-Rowell** [comment]
Hi Akinsho!

Thanks for your response, 
I'm busy with uni exams myself so hopefully I'll be able to try help out in the future 

Really appreciate, hope to PR soon

**Comment by michzappa** [comment]
hey @G-Rowell I see NvChad no longer uses this plugin so I assume you're not going to be taking a stab at this, is that correct? The window layout is kinda important to my workflow so if not I can try, though it might be a bit before I have enough time/understanding of the existing code.

**Comment by michzappa** [comment]
I've tried my hand at the "save settings then autocmd to re-set them" approach but despite the settings appearing to change in the plugin code itself the change is not reflected in neovim itself. In the meantime I'm trying to get an actual debugger setup in neovim to see this code at runtime, but that's not yielding great results so far.

https://github.com/michzappa/toggleterm.nvim/commit/07ad2bc9539be31eff7d3e2df9377e355dc70471

**Comment by akinsho** [comment]
@michzappa I haven't looked too closely but hiding a toggleterm is not a TermClose event, since that relates to actually ending the terminal process. The event should probably be BufHidden

**Comment by michzappa** [comment]
Ah. My workflow with the window direction does close the terminal so I was seeing the TermClose event trigger. But I'll try BufHidden later and see how that works, thanks for the tip.

**Comment by michzappa** [comment]
It seems that by the time BufHidden gets reached `terms.identify()` yields nil since the terminal buffer is no longer visible. I then tried to just set the values of `vim.wo.number` and `vim.wo.relativenumber` with the result of `vim.api.nvim_get_current_win()` but still no change in the window. The lines are definitely executing so I'm not sure what else there is to try at this level.

**Comment by akinsho** [comment]
@michzappa I think just setting the values with current window won't work since that was the widow whose values were already changed. I think if no clear autocommand is available, although there might be one, and it's just a matter of digging through the vim help, you could also a restore settings function to toggling and if the terminal being toggle is a window then call restore setting and re-apply them that way. One other way to test things than trying to re-apply the exact values is using something like `setlocal number< relativenumber<` see `:h setglobal` and other similar functions, just to see if things are triggering as expected.

**Comment by G-Rowell** [comment]
Hey,

sorry for being unresponsive to my own issue.

I don't really use Toggleterm myself anymore, but if @akinsho wanted help I'd be more than happy to.

Let me know if I need to do anything here


G

**Comment by akinsho** [comment]
@michzappa I've actually been thinking about this a lot and I actually think a much cleaner solution to this is to remove the `window` mode entirely and just use a tab, trying to re-use the window is probably possible but tbh unnecessarily complex if the desired layout is just a full screen terminal that has it's own window settings then just opening a new tab with a terminal and then closing that tab is by far the simplest solution. Also in hindsight the window layout is redundant if there is a tab layout. There is is no specific advantage to replacing the current window vs opening a new tab for this purpose anyway.

**Comment by michzappa** [comment]
That makes a lot of sense, haven't really used tabs much in my very short (neo)vim usage but I see how that can separate the logic from messing with existing window's settings.

**Comment by akinsho** [comment]
It's actually pretty straightforward to add I tinkered with it a little in my lunch break and got it mostly working, I'll see if I have time to finish + document it later as well as add in a warning about documenting deprecating the window mode. That should close this issue off then 👍🏿

**Comment by michzappa** [comment]
Sounds like a plan, I look forward to seeing it. Thanks for your help with this issue!

**Comment by G-Rowell** [comment]
@akinsho 

Just want to say thanks again for all your efforts into this & many other plugins! 😁
